kunlun-csi-objs := kunlun-core.o kunlun-stream.o kunlun-stream-video.o

obj-$(CONFIG_VIDEO_SEMIDRIVE) += kunlun-csi.o

obj-$(CONFIG_VIDEO_SEMIDRIVE_PARALLEL) += kunlun-parallel.o
obj-$(CONFIG_VIDEO_SEMIDRIVE_MIPICSI2) += kunlun-mipi-csi2.o

obj-$(CONFIG_VIDEO_SEMIDRIVE_OV5640) += ov5640.o
obj-$(CONFIG_VIDEO_SEMIDRIVE_MAX9286) += max9286.o
