/*
 * __regs_ap_lvds.h
 *
 * Semidrive kunlun platform drm driver
 *
 * Copyright (C) 2019, Semidrive  Communications Inc.
 *
 * This file is licensed under a dual GPLv2 or X11 license.
 */

#ifndef _AP_APB_LVDS_REG_H
#define _AP_APB_LVDS_REG_H
//--------------------------------------------------------------------------
// IP Ref Info     : REG_AP_APB_LVDS
// RTL version     :
//--------------------------------------------------------------------------

//--------------------------------------------------------------------------
// Address Block Name : LVDS_APB_AB0
// Description        :
//--------------------------------------------------------------------------
#define LVDS_APB_AB0_BASE_ADDR 0x0
//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_LVDS_SOFT_RESET
// Register Offset : 0x0
// Description     :
//--------------------------------------------------------------------------
#define REG_AP_APB_LVDS_SOFT_RESET (LVDS_APB_AB0_BASE_ADDR + (0x0<<0))
#define SOFT_RESET_TRIM_MODE_FIELD_OFFSET 6
#define SOFT_RESET_TRIM_MODE_FIELD_SIZE 1
#define SOFT_RESET_RTE_CTL_FIELD_OFFSET 5
#define SOFT_RESET_RTE_CTL_FIELD_SIZE 1
#define SOFT_RESET_COMBINE_SOFT_RESET_FIELD_OFFSET 4
#define SOFT_RESET_COMBINE_SOFT_RESET_FIELD_SIZE 1
#define SOFT_RESET_CH3_SOFT_RESET_FIELD_OFFSET 3
#define SOFT_RESET_CH3_SOFT_RESET_FIELD_SIZE 1
#define SOFT_RESET_CH2_SOFT_RESET_FIELD_OFFSET 2
#define SOFT_RESET_CH2_SOFT_RESET_FIELD_SIZE 1
#define SOFT_RESET_CH1_SOFT_RESET_FIELD_OFFSET 1
#define SOFT_RESET_CH1_SOFT_RESET_FIELD_SIZE 1
#define SOFT_RESET_CH0_SOFT_RESET_FIELD_OFFSET 0
#define SOFT_RESET_CH0_SOFT_RESET_FIELD_SIZE 1

#define BIT_AP_APB_LVDS_SOFT_RESET_TRIM_MODE    (BIT_(6))
#define BIT_AP_APB_LVDS_SOFT_RESET_RTE_CTL    (BIT_(5))
#define BIT_AP_APB_LVDS_SOFT_RESET_COMBINE_SOFT_RESET    (BIT_(4))
#define BIT_AP_APB_LVDS_SOFT_RESET_CH3_SOFT_RESET    (BIT_(3))
#define BIT_AP_APB_LVDS_SOFT_RESET_CH2_SOFT_RESET    (BIT_(2))
#define BIT_AP_APB_LVDS_SOFT_RESET_CH1_SOFT_RESET    (BIT_(1))
#define BIT_AP_APB_LVDS_SOFT_RESET_CH0_SOFT_RESET    (BIT_(0))

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_LVDS_MUX_SEL
// Register Offset : 0x4
// Description     :
//--------------------------------------------------------------------------
#define REG_AP_APB_LVDS_MUX_SEL (LVDS_APB_AB0_BASE_ADDR + (0x4<<0))
#define MUX_SEL_MUX8_SEL_FIELD_OFFSET 19
#define MUX_SEL_MUX8_SEL_FIELD_SIZE 2
#define MUX_SEL_MUX7_SEL_FIELD_OFFSET 17
#define MUX_SEL_MUX7_SEL_FIELD_SIZE 2
#define MUX_SEL_MUX6_SEL_FIELD_OFFSET 15
#define MUX_SEL_MUX6_SEL_FIELD_SIZE 2
#define MUX_SEL_MUX5_SEL_FIELD_OFFSET 13
#define MUX_SEL_MUX5_SEL_FIELD_SIZE 2
#define MUX_SEL_MUX4_SEL_FIELD_OFFSET 12
#define MUX_SEL_MUX4_SEL_FIELD_SIZE 1
#define MUX_SEL_MUX3_SEL_FIELD_OFFSET 9
#define MUX_SEL_MUX3_SEL_FIELD_SIZE 3
#define MUX_SEL_MUX2_SEL_FIELD_OFFSET 6
#define MUX_SEL_MUX2_SEL_FIELD_SIZE 3
#define MUX_SEL_MUX1_SEL_FIELD_OFFSET 3
#define MUX_SEL_MUX1_SEL_FIELD_SIZE 3
#define MUX_SEL_MUX0_SEL_FIELD_OFFSET 0
#define MUX_SEL_MUX0_SEL_FIELD_SIZE 3

#define BIT_AP_APB_LVDS_MUX_SEL_MUX8_SEL_1    (BIT_(20))
#define BIT_AP_APB_LVDS_MUX_SEL_MUX8_SEL_0    (BIT_(19))
#define BIT_AP_APB_LVDS_MUX_SEL_MUX7_SEL_1    (BIT_(18))
#define BIT_AP_APB_LVDS_MUX_SEL_MUX7_SEL_0    (BIT_(17))
#define BIT_AP_APB_LVDS_MUX_SEL_MUX6_SEL_1    (BIT_(16))
#define BIT_AP_APB_LVDS_MUX_SEL_MUX6_SEL_0    (BIT_(15))
#define BIT_AP_APB_LVDS_MUX_SEL_MUX5_SEL_1    (BIT_(14))
#define BIT_AP_APB_LVDS_MUX_SEL_MUX5_SEL_0    (BIT_(13))
#define BIT_AP_APB_LVDS_MUX_SEL_MUX4_SEL    (BIT_(12))
#define BIT_AP_APB_LVDS_MUX_SEL_MUX3_SEL_2    (BIT_(11))
#define BIT_AP_APB_LVDS_MUX_SEL_MUX3_SEL_1    (BIT_(10))
#define BIT_AP_APB_LVDS_MUX_SEL_MUX3_SEL_0    (BIT_(9))
#define BIT_AP_APB_LVDS_MUX_SEL_MUX2_SEL_2    (BIT_(8))
#define BIT_AP_APB_LVDS_MUX_SEL_MUX2_SEL_1    (BIT_(7))
#define BIT_AP_APB_LVDS_MUX_SEL_MUX2_SEL_0    (BIT_(6))
#define BIT_AP_APB_LVDS_MUX_SEL_MUX1_SEL_2    (BIT_(5))
#define BIT_AP_APB_LVDS_MUX_SEL_MUX1_SEL_1    (BIT_(4))
#define BIT_AP_APB_LVDS_MUX_SEL_MUX1_SEL_0    (BIT_(3))
#define BIT_AP_APB_LVDS_MUX_SEL_MUX0_SEL_2    (BIT_(2))
#define BIT_AP_APB_LVDS_MUX_SEL_MUX0_SEL_1    (BIT_(1))
#define BIT_AP_APB_LVDS_MUX_SEL_MUX0_SEL_0    (BIT_(0))

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_LVDS_LVDS_COMBINE
// Register Offset : 0x8
// Description     :
//--------------------------------------------------------------------------
#define REG_AP_APB_LVDS_LVDS_COMBINE (LVDS_APB_AB0_BASE_ADDR + (0x8<<0))
#define LVDS_COMBINE_ENABLE_FIELD_OFFSET 29
#define LVDS_COMBINE_ENABLE_FIELD_SIZE 1
#define LVDS_COMBINE_COMBINE_MODE_FIELD_OFFSET 28
#define LVDS_COMBINE_COMBINE_MODE_FIELD_SIZE 1
#define LVDS_COMBINE_DATA_EN_POL_FIELD_OFFSET 27
#define LVDS_COMBINE_DATA_EN_POL_FIELD_SIZE 1
#define LVDS_COMBINE_HSYNC_POL_FIELD_OFFSET 26
#define LVDS_COMBINE_HSYNC_POL_FIELD_SIZE 1
#define LVDS_COMBINE_VSYNC_POL_FIELD_OFFSET 25
#define LVDS_COMBINE_VSYNC_POL_FIELD_SIZE 1
#define LVDS_COMBINE_CH_SWAP_FIELD_OFFSET 24
#define LVDS_COMBINE_CH_SWAP_FIELD_SIZE 1
#define LVDS_COMBINE_GAP_FIELD_OFFSET 16
#define LVDS_COMBINE_GAP_FIELD_SIZE 8
#define LVDS_COMBINE_VLD_HEIGHT_FIELD_OFFSET 0
#define LVDS_COMBINE_VLD_HEIGHT_FIELD_SIZE 16

#define BIT_AP_APB_LVDS_LVDS_COMBINE_ENABLE    (BIT_(29))
#define BIT_AP_APB_LVDS_LVDS_COMBINE_COMBINE_MODE    (BIT_(28))
#define BIT_AP_APB_LVDS_LVDS_COMBINE_DATA_EN_POL    (BIT_(27))
#define BIT_AP_APB_LVDS_LVDS_COMBINE_HSYNC_POL    (BIT_(26))
#define BIT_AP_APB_LVDS_LVDS_COMBINE_VSYNC_POL    (BIT_(25))
#define BIT_AP_APB_LVDS_LVDS_COMBINE_CH_SWAP    (BIT_(24))
#define BIT_AP_APB_LVDS_LVDS_COMBINE_GAP_7    (BIT_(23))
#define BIT_AP_APB_LVDS_LVDS_COMBINE_GAP_6    (BIT_(22))
#define BIT_AP_APB_LVDS_LVDS_COMBINE_GAP_5    (BIT_(21))
#define BIT_AP_APB_LVDS_LVDS_COMBINE_GAP_4    (BIT_(20))
#define BIT_AP_APB_LVDS_LVDS_COMBINE_GAP_3    (BIT_(19))
#define BIT_AP_APB_LVDS_LVDS_COMBINE_GAP_2    (BIT_(18))
#define BIT_AP_APB_LVDS_LVDS_COMBINE_GAP_1    (BIT_(17))
#define BIT_AP_APB_LVDS_LVDS_COMBINE_GAP_0    (BIT_(16))
#define BIT_AP_APB_LVDS_LVDS_COMBINE_VLD_HEIGHT_15    (BIT_(15))
#define BIT_AP_APB_LVDS_LVDS_COMBINE_VLD_HEIGHT_14    (BIT_(14))
#define BIT_AP_APB_LVDS_LVDS_COMBINE_VLD_HEIGHT_13    (BIT_(13))
#define BIT_AP_APB_LVDS_LVDS_COMBINE_VLD_HEIGHT_12    (BIT_(12))
#define BIT_AP_APB_LVDS_LVDS_COMBINE_VLD_HEIGHT_11    (BIT_(11))
#define BIT_AP_APB_LVDS_LVDS_COMBINE_VLD_HEIGHT_10    (BIT_(10))
#define BIT_AP_APB_LVDS_LVDS_COMBINE_VLD_HEIGHT_9    (BIT_(9))
#define BIT_AP_APB_LVDS_LVDS_COMBINE_VLD_HEIGHT_8    (BIT_(8))
#define BIT_AP_APB_LVDS_LVDS_COMBINE_VLD_HEIGHT_7    (BIT_(7))
#define BIT_AP_APB_LVDS_LVDS_COMBINE_VLD_HEIGHT_6    (BIT_(6))
#define BIT_AP_APB_LVDS_LVDS_COMBINE_VLD_HEIGHT_5    (BIT_(5))
#define BIT_AP_APB_LVDS_LVDS_COMBINE_VLD_HEIGHT_4    (BIT_(4))
#define BIT_AP_APB_LVDS_LVDS_COMBINE_VLD_HEIGHT_3    (BIT_(3))
#define BIT_AP_APB_LVDS_LVDS_COMBINE_VLD_HEIGHT_2    (BIT_(2))
#define BIT_AP_APB_LVDS_LVDS_COMBINE_VLD_HEIGHT_1    (BIT_(1))
#define BIT_AP_APB_LVDS_LVDS_COMBINE_VLD_HEIGHT_0    (BIT_(0))

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_LVDS_LVDS_BIAS_SET
// Register Offset : 0xc
// Description     :
//--------------------------------------------------------------------------
#define REG_AP_APB_LVDS_LVDS_BIAS_SET (LVDS_APB_AB0_BASE_ADDR + (0xc<<0))
#define LVDS_BIAS_SET_BIAS_TRIM_FIELD_OFFSET 2
#define LVDS_BIAS_SET_BIAS_TRIM_FIELD_SIZE 2
#define LVDS_BIAS_SET_BIAS_SELVDD_FIELD_OFFSET 1
#define LVDS_BIAS_SET_BIAS_SELVDD_FIELD_SIZE 1
#define LVDS_BIAS_SET_BIAS_EN_FIELD_OFFSET 0
#define LVDS_BIAS_SET_BIAS_EN_FIELD_SIZE 1

#define BIT_AP_APB_LVDS_LVDS_BIAS_SET_BIAS_TRIM_1    (BIT_(3))
#define BIT_AP_APB_LVDS_LVDS_BIAS_SET_BIAS_TRIM_0    (BIT_(2))
#define BIT_AP_APB_LVDS_LVDS_BIAS_SET_BIAS_SELVDD    (BIT_(1))
#define BIT_AP_APB_LVDS_LVDS_BIAS_SET_BIAS_EN    (BIT_(0))

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_LVDS_TEST_CFG_0
// Register Offset : 0x100
// Description     :
//--------------------------------------------------------------------------
#define REG_AP_APB_LVDS_TEST_CFG_0 (LVDS_APB_AB0_BASE_ADDR + (0x100<<0))
#define TEST_CFG_0_ENABLE_FIELD_OFFSET 7
#define TEST_CFG_0_ENABLE_FIELD_SIZE 1
#define TEST_CFG_0_DATA_FIELD_OFFSET 0
#define TEST_CFG_0_DATA_FIELD_SIZE 7

#define BIT_AP_APB_LVDS_TEST_CFG_0_ENABLE    (BIT_(7))
#define BIT_AP_APB_LVDS_TEST_CFG_0_DATA_6    (BIT_(6))
#define BIT_AP_APB_LVDS_TEST_CFG_0_DATA_5    (BIT_(5))
#define BIT_AP_APB_LVDS_TEST_CFG_0_DATA_4    (BIT_(4))
#define BIT_AP_APB_LVDS_TEST_CFG_0_DATA_3    (BIT_(3))
#define BIT_AP_APB_LVDS_TEST_CFG_0_DATA_2    (BIT_(2))
#define BIT_AP_APB_LVDS_TEST_CFG_0_DATA_1    (BIT_(1))
#define BIT_AP_APB_LVDS_TEST_CFG_0_DATA_0    (BIT_(0))

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_LVDS_TEST_CFG_1
// Register Offset : 0x104
// Description     :
//--------------------------------------------------------------------------
#define REG_AP_APB_LVDS_TEST_CFG_1 (LVDS_APB_AB0_BASE_ADDR + (0x104<<0))
#define TEST_CFG_1_ENABLE_FIELD_OFFSET 7
#define TEST_CFG_1_ENABLE_FIELD_SIZE 1
#define TEST_CFG_1_DATA_FIELD_OFFSET 0
#define TEST_CFG_1_DATA_FIELD_SIZE 7

#define BIT_AP_APB_LVDS_TEST_CFG_1_ENABLE    (BIT_(7))
#define BIT_AP_APB_LVDS_TEST_CFG_1_DATA_6    (BIT_(6))
#define BIT_AP_APB_LVDS_TEST_CFG_1_DATA_5    (BIT_(5))
#define BIT_AP_APB_LVDS_TEST_CFG_1_DATA_4    (BIT_(4))
#define BIT_AP_APB_LVDS_TEST_CFG_1_DATA_3    (BIT_(3))
#define BIT_AP_APB_LVDS_TEST_CFG_1_DATA_2    (BIT_(2))
#define BIT_AP_APB_LVDS_TEST_CFG_1_DATA_1    (BIT_(1))
#define BIT_AP_APB_LVDS_TEST_CFG_1_DATA_0    (BIT_(0))

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_LVDS_LVDS_CH_0
// Register Offset : 0x10000
// Description     :
//--------------------------------------------------------------------------
#define REG_AP_APB_LVDS_LVDS_CH_0 (LVDS_APB_AB0_BASE_ADDR + (0x10000<<0))
#define LVDS_CH_0_ENABLE_FIELD_OFFSET 31
#define LVDS_CH_0_ENABLE_FIELD_SIZE 1
#define LVDS_CH_0_MUX_FIELD_OFFSET 23
#define LVDS_CH_0_MUX_FIELD_SIZE 2
#define LVDS_CH_0_DUALODD_FIELD_OFFSET 22
#define LVDS_CH_0_DUALODD_FIELD_SIZE 1
#define LVDS_CH_0_LANE_UPDATE_FIELD_OFFSET 7
#define LVDS_CH_0_LANE_UPDATE_FIELD_SIZE 15
#define LVDS_CH_0_FRAME_MASK_FIELD_OFFSET 5
#define LVDS_CH_0_FRAME_MASK_FIELD_SIZE 2
#define LVDS_CH_0_VSYNC_POL_FIELD_OFFSET 4
#define LVDS_CH_0_VSYNC_POL_FIELD_SIZE 1
#define LVDS_CH_0_FORMAT_FIELD_OFFSET 3
#define LVDS_CH_0_FORMAT_FIELD_SIZE 1
#define LVDS_CH_0_BPP_FIELD_OFFSET 1
#define LVDS_CH_0_BPP_FIELD_SIZE 2
#define LVDS_CH_0_DUALMODE_FIELD_OFFSET 0
#define LVDS_CH_0_DUALMODE_FIELD_SIZE 1

#define BIT_AP_APB_LVDS_LVDS_CH_0_ENABLE    (BIT_(31))
#define BIT_AP_APB_LVDS_LVDS_CH_0_MUX_1    (BIT_(24))
#define BIT_AP_APB_LVDS_LVDS_CH_0_MUX_0    (BIT_(23))
#define BIT_AP_APB_LVDS_LVDS_CH_0_DUALODD    (BIT_(22))
#define BIT_AP_APB_LVDS_LVDS_CH_0_LANE_UPDATE_14    (BIT_(21))
#define BIT_AP_APB_LVDS_LVDS_CH_0_LANE_UPDATE_13    (BIT_(20))
#define BIT_AP_APB_LVDS_LVDS_CH_0_LANE_UPDATE_12    (BIT_(19))
#define BIT_AP_APB_LVDS_LVDS_CH_0_LANE_UPDATE_11    (BIT_(18))
#define BIT_AP_APB_LVDS_LVDS_CH_0_LANE_UPDATE_10    (BIT_(17))
#define BIT_AP_APB_LVDS_LVDS_CH_0_LANE_UPDATE_9    (BIT_(16))
#define BIT_AP_APB_LVDS_LVDS_CH_0_LANE_UPDATE_8    (BIT_(15))
#define BIT_AP_APB_LVDS_LVDS_CH_0_LANE_UPDATE_7    (BIT_(14))
#define BIT_AP_APB_LVDS_LVDS_CH_0_LANE_UPDATE_6    (BIT_(13))
#define BIT_AP_APB_LVDS_LVDS_CH_0_LANE_UPDATE_5    (BIT_(12))
#define BIT_AP_APB_LVDS_LVDS_CH_0_LANE_UPDATE_4    (BIT_(11))
#define BIT_AP_APB_LVDS_LVDS_CH_0_LANE_UPDATE_3    (BIT_(10))
#define BIT_AP_APB_LVDS_LVDS_CH_0_LANE_UPDATE_2    (BIT_(9))
#define BIT_AP_APB_LVDS_LVDS_CH_0_LANE_UPDATE_1    (BIT_(8))
#define BIT_AP_APB_LVDS_LVDS_CH_0_LANE_UPDATE_0    (BIT_(7))
#define BIT_AP_APB_LVDS_LVDS_CH_0_FRAME_MASK_1    (BIT_(6))
#define BIT_AP_APB_LVDS_LVDS_CH_0_FRAME_MASK_0    (BIT_(5))
#define BIT_AP_APB_LVDS_LVDS_CH_0_VSYNC_POL    (BIT_(4))
#define BIT_AP_APB_LVDS_LVDS_CH_0_FORMAT    (BIT_(3))
#define BIT_AP_APB_LVDS_LVDS_CH_0_BPP_1    (BIT_(2))
#define BIT_AP_APB_LVDS_LVDS_CH_0_BPP_0    (BIT_(1))
#define BIT_AP_APB_LVDS_LVDS_CH_0_DUALMODE    (BIT_(0))

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_LVDS_LVDS_CLOCK_0
// Register Offset : 0x10004
// Description     :
//--------------------------------------------------------------------------
#define REG_AP_APB_LVDS_LVDS_CLOCK_0 (LVDS_APB_AB0_BASE_ADDR + (0x10004<<0))
#define LVDS_CLOCK_0_DIV_NUM_DBG_FIELD_OFFSET 11
#define LVDS_CLOCK_0_DIV_NUM_DBG_FIELD_SIZE 4
#define LVDS_CLOCK_0_DIV_NUM_LVDS_FIELD_OFFSET 7
#define LVDS_CLOCK_0_DIV_NUM_LVDS_FIELD_SIZE 4
#define LVDS_CLOCK_0_GATING_ACK_FIELD_OFFSET 6
#define LVDS_CLOCK_0_GATING_ACK_FIELD_SIZE 1
#define LVDS_CLOCK_0_GATING_EN_FIELD_OFFSET 1
#define LVDS_CLOCK_0_GATING_EN_FIELD_SIZE 5
#define LVDS_CLOCK_0_SRC_SEL_FIELD_OFFSET 0
#define LVDS_CLOCK_0_SRC_SEL_FIELD_SIZE 1

#define BIT_AP_APB_LVDS_LVDS_CLOCK_0_DIV_NUM_DBG_3    (BIT_(14))
#define BIT_AP_APB_LVDS_LVDS_CLOCK_0_DIV_NUM_DBG_2    (BIT_(13))
#define BIT_AP_APB_LVDS_LVDS_CLOCK_0_DIV_NUM_DBG_1    (BIT_(12))
#define BIT_AP_APB_LVDS_LVDS_CLOCK_0_DIV_NUM_DBG_0    (BIT_(11))
#define BIT_AP_APB_LVDS_LVDS_CLOCK_0_DIV_NUM_LVDS_3    (BIT_(10))
#define BIT_AP_APB_LVDS_LVDS_CLOCK_0_DIV_NUM_LVDS_2    (BIT_(9))
#define BIT_AP_APB_LVDS_LVDS_CLOCK_0_DIV_NUM_LVDS_1    (BIT_(8))
#define BIT_AP_APB_LVDS_LVDS_CLOCK_0_DIV_NUM_LVDS_0    (BIT_(7))
#define BIT_AP_APB_LVDS_LVDS_CLOCK_0_GATING_ACK    (BIT_(6))
#define BIT_AP_APB_LVDS_LVDS_CLOCK_0_GATING_EN_4    (BIT_(5))
#define BIT_AP_APB_LVDS_LVDS_CLOCK_0_GATING_EN_3    (BIT_(4))
#define BIT_AP_APB_LVDS_LVDS_CLOCK_0_GATING_EN_2    (BIT_(3))
#define BIT_AP_APB_LVDS_LVDS_CLOCK_0_GATING_EN_1    (BIT_(2))
#define BIT_AP_APB_LVDS_LVDS_CLOCK_0_GATING_EN_0    (BIT_(1))
#define BIT_AP_APB_LVDS_LVDS_CLOCK_0_SRC_SEL    (BIT_(0))

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_LVDS_LVDS_CH0_PAD_COM_SET
// Register Offset : 0x10008
// Description     :
//--------------------------------------------------------------------------
#define REG_AP_APB_LVDS_LVDS_CH0_PAD_COM_SET (LVDS_APB_AB0_BASE_ADDR + (0x10008<<0))
#define LVDS_CH0_PAD_COM_SET_LVDS_TRIM_FIELD_OFFSET 14
#define LVDS_CH0_PAD_COM_SET_LVDS_TRIM_FIELD_SIZE 3
#define LVDS_CH0_PAD_COM_SET_TEST_TXD_P_FIELD_OFFSET 13
#define LVDS_CH0_PAD_COM_SET_TEST_TXD_P_FIELD_SIZE 1
#define LVDS_CH0_PAD_COM_SET_TEST_TXD_N_FIELD_OFFSET 12
#define LVDS_CH0_PAD_COM_SET_TEST_TXD_N_FIELD_SIZE 1
#define LVDS_CH0_PAD_COM_SET_TEST_SCHMITT_EN_FIELD_OFFSET 11
#define LVDS_CH0_PAD_COM_SET_TEST_SCHMITT_EN_FIELD_SIZE 1
#define LVDS_CH0_PAD_COM_SET_TEST_RXEN_FIELD_OFFSET 10
#define LVDS_CH0_PAD_COM_SET_TEST_RXEN_FIELD_SIZE 1
#define LVDS_CH0_PAD_COM_SET_TEST_RXCM_EN_FIELD_OFFSET 9
#define LVDS_CH0_PAD_COM_SET_TEST_RXCM_EN_FIELD_SIZE 1
#define LVDS_CH0_PAD_COM_SET_TEST_PULLDN_FIELD_OFFSET 8
#define LVDS_CH0_PAD_COM_SET_TEST_PULLDN_FIELD_SIZE 1
#define LVDS_CH0_PAD_COM_SET_TEST_OEN_P_FIELD_OFFSET 7
#define LVDS_CH0_PAD_COM_SET_TEST_OEN_P_FIELD_SIZE 1
#define LVDS_CH0_PAD_COM_SET_TEST_OEN_N_FIELD_OFFSET 6
#define LVDS_CH0_PAD_COM_SET_TEST_OEN_N_FIELD_SIZE 1
#define LVDS_CH0_PAD_COM_SET_TEST_IEN_P_FIELD_OFFSET 5
#define LVDS_CH0_PAD_COM_SET_TEST_IEN_P_FIELD_SIZE 1
#define LVDS_CH0_PAD_COM_SET_TEST_IEN_N_FIELD_OFFSET 4
#define LVDS_CH0_PAD_COM_SET_TEST_IEN_N_FIELD_SIZE 1

#define BIT_AP_APB_LVDS_LVDS_CH0_PAD_COM_SET_LVDS_TRIM_2    (BIT_(16))
#define BIT_AP_APB_LVDS_LVDS_CH0_PAD_COM_SET_LVDS_TRIM_1    (BIT_(15))
#define BIT_AP_APB_LVDS_LVDS_CH0_PAD_COM_SET_LVDS_TRIM_0    (BIT_(14))
#define BIT_AP_APB_LVDS_LVDS_CH0_PAD_COM_SET_TEST_TXD_P    (BIT_(13))
#define BIT_AP_APB_LVDS_LVDS_CH0_PAD_COM_SET_TEST_TXD_N    (BIT_(12))
#define BIT_AP_APB_LVDS_LVDS_CH0_PAD_COM_SET_TEST_SCHMITT_EN    (BIT_(11))
#define BIT_AP_APB_LVDS_LVDS_CH0_PAD_COM_SET_TEST_RXEN    (BIT_(10))
#define BIT_AP_APB_LVDS_LVDS_CH0_PAD_COM_SET_TEST_RXCM_EN    (BIT_(9))
#define BIT_AP_APB_LVDS_LVDS_CH0_PAD_COM_SET_TEST_PULLDN    (BIT_(8))
#define BIT_AP_APB_LVDS_LVDS_CH0_PAD_COM_SET_TEST_OEN_P    (BIT_(7))
#define BIT_AP_APB_LVDS_LVDS_CH0_PAD_COM_SET_TEST_OEN_N    (BIT_(6))
#define BIT_AP_APB_LVDS_LVDS_CH0_PAD_COM_SET_TEST_IEN_P    (BIT_(5))
#define BIT_AP_APB_LVDS_LVDS_CH0_PAD_COM_SET_TEST_IEN_N    (BIT_(4))

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_LVDS_LVDS_CH0_PAD_SET
// Register Offset : 0x10010
// Description     :
//--------------------------------------------------------------------------
#define REG_AP_APB_LVDS_LVDS_CH0_PAD_SET (LVDS_APB_AB0_BASE_ADDR + (0x10010<<0))
#define LVDS_CH0_PAD_SET_RXDA_FIELD_OFFSET 11
#define LVDS_CH0_PAD_SET_RXDA_FIELD_SIZE 1
#define LVDS_CH0_PAD_SET_RXD_P_FIELD_OFFSET 10
#define LVDS_CH0_PAD_SET_RXD_P_FIELD_SIZE 1
#define LVDS_CH0_PAD_SET_RXD_N_FIELD_OFFSET 9
#define LVDS_CH0_PAD_SET_RXD_N_FIELD_SIZE 1
#define LVDS_CH0_PAD_SET_VBIAS_SEL_FIELD_OFFSET 8
#define LVDS_CH0_PAD_SET_VBIAS_SEL_FIELD_SIZE 1
#define LVDS_CH0_PAD_SET_TXEN_FIELD_OFFSET 7
#define LVDS_CH0_PAD_SET_TXEN_FIELD_SIZE 1
#define LVDS_CH0_PAD_SET_TXDRV_FIELD_OFFSET 3
#define LVDS_CH0_PAD_SET_TXDRV_FIELD_SIZE 4
#define LVDS_CH0_PAD_SET_TX_CM_FIELD_OFFSET 2
#define LVDS_CH0_PAD_SET_TX_CM_FIELD_SIZE 1
#define LVDS_CH0_PAD_SET_RTERM_EN_FIELD_OFFSET 1
#define LVDS_CH0_PAD_SET_RTERM_EN_FIELD_SIZE 1
#define LVDS_CH0_PAD_SET_BIAS_EN_FIELD_OFFSET 0
#define LVDS_CH0_PAD_SET_BIAS_EN_FIELD_SIZE 1

#define BIT_AP_APB_LVDS_LVDS_CH0_PAD_SET_RXDA    (BIT_(11))
#define BIT_AP_APB_LVDS_LVDS_CH0_PAD_SET_RXD_P    (BIT_(10))
#define BIT_AP_APB_LVDS_LVDS_CH0_PAD_SET_RXD_N    (BIT_(9))
#define BIT_AP_APB_LVDS_LVDS_CH0_PAD_SET_VBIAS_SEL    (BIT_(8))
#define BIT_AP_APB_LVDS_LVDS_CH0_PAD_SET_TXEN    (BIT_(7))
#define BIT_AP_APB_LVDS_LVDS_CH0_PAD_SET_TXDRV_3    (BIT_(6))
#define BIT_AP_APB_LVDS_LVDS_CH0_PAD_SET_TXDRV_2    (BIT_(5))
#define BIT_AP_APB_LVDS_LVDS_CH0_PAD_SET_TXDRV_1    (BIT_(4))
#define BIT_AP_APB_LVDS_LVDS_CH0_PAD_SET_TXDRV_0    (BIT_(3))
#define BIT_AP_APB_LVDS_LVDS_CH0_PAD_SET_TX_CM    (BIT_(2))
#define BIT_AP_APB_LVDS_LVDS_CH0_PAD_SET_RTERM_EN    (BIT_(1))
#define BIT_AP_APB_LVDS_LVDS_CH0_PAD_SET_BIAS_EN    (BIT_(0))

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_LVDS_LVDS_CH_1
// Register Offset : 0x20000
// Description     :
//--------------------------------------------------------------------------
#define REG_AP_APB_LVDS_LVDS_CH_1 (LVDS_APB_AB0_BASE_ADDR + (0x20000<<0))
#define LVDS_CH_1_ENABLE_FIELD_OFFSET 31
#define LVDS_CH_1_ENABLE_FIELD_SIZE 1
#define LVDS_CH_1_MUX_FIELD_OFFSET 23
#define LVDS_CH_1_MUX_FIELD_SIZE 2
#define LVDS_CH_1_DUALODD_FIELD_OFFSET 22
#define LVDS_CH_1_DUALODD_FIELD_SIZE 1
#define LVDS_CH_1_LANE_UPDATE_FIELD_OFFSET 7
#define LVDS_CH_1_LANE_UPDATE_FIELD_SIZE 15
#define LVDS_CH_1_FRAME_MASK_FIELD_OFFSET 5
#define LVDS_CH_1_FRAME_MASK_FIELD_SIZE 2
#define LVDS_CH_1_VSYNC_POL_FIELD_OFFSET 4
#define LVDS_CH_1_VSYNC_POL_FIELD_SIZE 1
#define LVDS_CH_1_FORMAT_FIELD_OFFSET 3
#define LVDS_CH_1_FORMAT_FIELD_SIZE 1
#define LVDS_CH_1_BPP_FIELD_OFFSET 1
#define LVDS_CH_1_BPP_FIELD_SIZE 2
#define LVDS_CH_1_DUALMODE_FIELD_OFFSET 0
#define LVDS_CH_1_DUALMODE_FIELD_SIZE 1

#define BIT_AP_APB_LVDS_LVDS_CH_1_ENABLE    (BIT_(31))
#define BIT_AP_APB_LVDS_LVDS_CH_1_MUX_1    (BIT_(24))
#define BIT_AP_APB_LVDS_LVDS_CH_1_MUX_0    (BIT_(23))
#define BIT_AP_APB_LVDS_LVDS_CH_1_DUALODD    (BIT_(22))
#define BIT_AP_APB_LVDS_LVDS_CH_1_LANE_UPDATE_14    (BIT_(21))
#define BIT_AP_APB_LVDS_LVDS_CH_1_LANE_UPDATE_13    (BIT_(20))
#define BIT_AP_APB_LVDS_LVDS_CH_1_LANE_UPDATE_12    (BIT_(19))
#define BIT_AP_APB_LVDS_LVDS_CH_1_LANE_UPDATE_11    (BIT_(18))
#define BIT_AP_APB_LVDS_LVDS_CH_1_LANE_UPDATE_10    (BIT_(17))
#define BIT_AP_APB_LVDS_LVDS_CH_1_LANE_UPDATE_9    (BIT_(16))
#define BIT_AP_APB_LVDS_LVDS_CH_1_LANE_UPDATE_8    (BIT_(15))
#define BIT_AP_APB_LVDS_LVDS_CH_1_LANE_UPDATE_7    (BIT_(14))
#define BIT_AP_APB_LVDS_LVDS_CH_1_LANE_UPDATE_6    (BIT_(13))
#define BIT_AP_APB_LVDS_LVDS_CH_1_LANE_UPDATE_5    (BIT_(12))
#define BIT_AP_APB_LVDS_LVDS_CH_1_LANE_UPDATE_4    (BIT_(11))
#define BIT_AP_APB_LVDS_LVDS_CH_1_LANE_UPDATE_3    (BIT_(10))
#define BIT_AP_APB_LVDS_LVDS_CH_1_LANE_UPDATE_2    (BIT_(9))
#define BIT_AP_APB_LVDS_LVDS_CH_1_LANE_UPDATE_1    (BIT_(8))
#define BIT_AP_APB_LVDS_LVDS_CH_1_LANE_UPDATE_0    (BIT_(7))
#define BIT_AP_APB_LVDS_LVDS_CH_1_FRAME_MASK_1    (BIT_(6))
#define BIT_AP_APB_LVDS_LVDS_CH_1_FRAME_MASK_0    (BIT_(5))
#define BIT_AP_APB_LVDS_LVDS_CH_1_VSYNC_POL    (BIT_(4))
#define BIT_AP_APB_LVDS_LVDS_CH_1_FORMAT    (BIT_(3))
#define BIT_AP_APB_LVDS_LVDS_CH_1_BPP_1    (BIT_(2))
#define BIT_AP_APB_LVDS_LVDS_CH_1_BPP_0    (BIT_(1))
#define BIT_AP_APB_LVDS_LVDS_CH_1_DUALMODE    (BIT_(0))

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_LVDS_LVDS_CLOCK_1
// Register Offset : 0x20004
// Description     :
//--------------------------------------------------------------------------
#define REG_AP_APB_LVDS_LVDS_CLOCK_1 (LVDS_APB_AB0_BASE_ADDR + (0x20004<<0))
#define LVDS_CLOCK_1_DIV_NUM_DBG_FIELD_OFFSET 11
#define LVDS_CLOCK_1_DIV_NUM_DBG_FIELD_SIZE 4
#define LVDS_CLOCK_1_DIV_NUM_LVDS_FIELD_OFFSET 7
#define LVDS_CLOCK_1_DIV_NUM_LVDS_FIELD_SIZE 4
#define LVDS_CLOCK_1_GATING_ACK_FIELD_OFFSET 6
#define LVDS_CLOCK_1_GATING_ACK_FIELD_SIZE 1
#define LVDS_CLOCK_1_GATING_EN_FIELD_OFFSET 1
#define LVDS_CLOCK_1_GATING_EN_FIELD_SIZE 5
#define LVDS_CLOCK_1_SRC_SEL_FIELD_OFFSET 0
#define LVDS_CLOCK_1_SRC_SEL_FIELD_SIZE 1

#define BIT_AP_APB_LVDS_LVDS_CLOCK_1_DIV_NUM_DBG_3    (BIT_(14))
#define BIT_AP_APB_LVDS_LVDS_CLOCK_1_DIV_NUM_DBG_2    (BIT_(13))
#define BIT_AP_APB_LVDS_LVDS_CLOCK_1_DIV_NUM_DBG_1    (BIT_(12))
#define BIT_AP_APB_LVDS_LVDS_CLOCK_1_DIV_NUM_DBG_0    (BIT_(11))
#define BIT_AP_APB_LVDS_LVDS_CLOCK_1_DIV_NUM_LVDS_3    (BIT_(10))
#define BIT_AP_APB_LVDS_LVDS_CLOCK_1_DIV_NUM_LVDS_2    (BIT_(9))
#define BIT_AP_APB_LVDS_LVDS_CLOCK_1_DIV_NUM_LVDS_1    (BIT_(8))
#define BIT_AP_APB_LVDS_LVDS_CLOCK_1_DIV_NUM_LVDS_0    (BIT_(7))
#define BIT_AP_APB_LVDS_LVDS_CLOCK_1_GATING_ACK    (BIT_(6))
#define BIT_AP_APB_LVDS_LVDS_CLOCK_1_GATING_EN_4    (BIT_(5))
#define BIT_AP_APB_LVDS_LVDS_CLOCK_1_GATING_EN_3    (BIT_(4))
#define BIT_AP_APB_LVDS_LVDS_CLOCK_1_GATING_EN_2    (BIT_(3))
#define BIT_AP_APB_LVDS_LVDS_CLOCK_1_GATING_EN_1    (BIT_(2))
#define BIT_AP_APB_LVDS_LVDS_CLOCK_1_GATING_EN_0    (BIT_(1))
#define BIT_AP_APB_LVDS_LVDS_CLOCK_1_SRC_SEL    (BIT_(0))

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_LVDS_LVDS_CH1_PAD_COM_SET
// Register Offset : 0x20008
// Description     :
//--------------------------------------------------------------------------
#define REG_AP_APB_LVDS_LVDS_CH1_PAD_COM_SET (LVDS_APB_AB0_BASE_ADDR + (0x20008<<0))
#define LVDS_CH1_PAD_COM_SET_LVDS_TRIM_FIELD_OFFSET 14
#define LVDS_CH1_PAD_COM_SET_LVDS_TRIM_FIELD_SIZE 3
#define LVDS_CH1_PAD_COM_SET_TEST_TXD_P_FIELD_OFFSET 13
#define LVDS_CH1_PAD_COM_SET_TEST_TXD_P_FIELD_SIZE 1
#define LVDS_CH1_PAD_COM_SET_TEST_TXD_N_FIELD_OFFSET 12
#define LVDS_CH1_PAD_COM_SET_TEST_TXD_N_FIELD_SIZE 1
#define LVDS_CH1_PAD_COM_SET_TEST_SCHMITT_EN_FIELD_OFFSET 11
#define LVDS_CH1_PAD_COM_SET_TEST_SCHMITT_EN_FIELD_SIZE 1
#define LVDS_CH1_PAD_COM_SET_TEST_RXEN_FIELD_OFFSET 10
#define LVDS_CH1_PAD_COM_SET_TEST_RXEN_FIELD_SIZE 1
#define LVDS_CH1_PAD_COM_SET_TEST_RXCM_EN_FIELD_OFFSET 9
#define LVDS_CH1_PAD_COM_SET_TEST_RXCM_EN_FIELD_SIZE 1
#define LVDS_CH1_PAD_COM_SET_TEST_PULLDN_FIELD_OFFSET 8
#define LVDS_CH1_PAD_COM_SET_TEST_PULLDN_FIELD_SIZE 1
#define LVDS_CH1_PAD_COM_SET_TEST_OEN_P_FIELD_OFFSET 7
#define LVDS_CH1_PAD_COM_SET_TEST_OEN_P_FIELD_SIZE 1
#define LVDS_CH1_PAD_COM_SET_TEST_OEN_N_FIELD_OFFSET 6
#define LVDS_CH1_PAD_COM_SET_TEST_OEN_N_FIELD_SIZE 1
#define LVDS_CH1_PAD_COM_SET_TEST_IEN_P_FIELD_OFFSET 5
#define LVDS_CH1_PAD_COM_SET_TEST_IEN_P_FIELD_SIZE 1
#define LVDS_CH1_PAD_COM_SET_TEST_IEN_N_FIELD_OFFSET 4
#define LVDS_CH1_PAD_COM_SET_TEST_IEN_N_FIELD_SIZE 1

#define BIT_AP_APB_LVDS_LVDS_CH1_PAD_COM_SET_LVDS_TRIM_2    (BIT_(16))
#define BIT_AP_APB_LVDS_LVDS_CH1_PAD_COM_SET_LVDS_TRIM_1    (BIT_(15))
#define BIT_AP_APB_LVDS_LVDS_CH1_PAD_COM_SET_LVDS_TRIM_0    (BIT_(14))
#define BIT_AP_APB_LVDS_LVDS_CH1_PAD_COM_SET_TEST_TXD_P    (BIT_(13))
#define BIT_AP_APB_LVDS_LVDS_CH1_PAD_COM_SET_TEST_TXD_N    (BIT_(12))
#define BIT_AP_APB_LVDS_LVDS_CH1_PAD_COM_SET_TEST_SCHMITT_EN    (BIT_(11))
#define BIT_AP_APB_LVDS_LVDS_CH1_PAD_COM_SET_TEST_RXEN    (BIT_(10))
#define BIT_AP_APB_LVDS_LVDS_CH1_PAD_COM_SET_TEST_RXCM_EN    (BIT_(9))
#define BIT_AP_APB_LVDS_LVDS_CH1_PAD_COM_SET_TEST_PULLDN    (BIT_(8))
#define BIT_AP_APB_LVDS_LVDS_CH1_PAD_COM_SET_TEST_OEN_P    (BIT_(7))
#define BIT_AP_APB_LVDS_LVDS_CH1_PAD_COM_SET_TEST_OEN_N    (BIT_(6))
#define BIT_AP_APB_LVDS_LVDS_CH1_PAD_COM_SET_TEST_IEN_P    (BIT_(5))
#define BIT_AP_APB_LVDS_LVDS_CH1_PAD_COM_SET_TEST_IEN_N    (BIT_(4))

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_LVDS_LVDS_CH1_PAD_SET
// Register Offset : 0x20010
// Description     :
//--------------------------------------------------------------------------
#define REG_AP_APB_LVDS_LVDS_CH1_PAD_SET (LVDS_APB_AB0_BASE_ADDR + (0x20010<<0))
#define LVDS_CH1_PAD_SET_RXDA_FIELD_OFFSET 11
#define LVDS_CH1_PAD_SET_RXDA_FIELD_SIZE 1
#define LVDS_CH1_PAD_SET_RXD_P_FIELD_OFFSET 10
#define LVDS_CH1_PAD_SET_RXD_P_FIELD_SIZE 1
#define LVDS_CH1_PAD_SET_RXD_N_FIELD_OFFSET 9
#define LVDS_CH1_PAD_SET_RXD_N_FIELD_SIZE 1
#define LVDS_CH1_PAD_SET_VBIAS_SEL_FIELD_OFFSET 8
#define LVDS_CH1_PAD_SET_VBIAS_SEL_FIELD_SIZE 1
#define LVDS_CH1_PAD_SET_TXEN_FIELD_OFFSET 7
#define LVDS_CH1_PAD_SET_TXEN_FIELD_SIZE 1
#define LVDS_CH1_PAD_SET_TXDRV_FIELD_OFFSET 3
#define LVDS_CH1_PAD_SET_TXDRV_FIELD_SIZE 4
#define LVDS_CH1_PAD_SET_TX_CM_FIELD_OFFSET 2
#define LVDS_CH1_PAD_SET_TX_CM_FIELD_SIZE 1
#define LVDS_CH1_PAD_SET_RTERM_EN_FIELD_OFFSET 1
#define LVDS_CH1_PAD_SET_RTERM_EN_FIELD_SIZE 1
#define LVDS_CH1_PAD_SET_BIAS_EN_FIELD_OFFSET 0
#define LVDS_CH1_PAD_SET_BIAS_EN_FIELD_SIZE 1

#define BIT_AP_APB_LVDS_LVDS_CH1_PAD_SET_RXDA    (BIT_(11))
#define BIT_AP_APB_LVDS_LVDS_CH1_PAD_SET_RXD_P    (BIT_(10))
#define BIT_AP_APB_LVDS_LVDS_CH1_PAD_SET_RXD_N    (BIT_(9))
#define BIT_AP_APB_LVDS_LVDS_CH1_PAD_SET_VBIAS_SEL    (BIT_(8))
#define BIT_AP_APB_LVDS_LVDS_CH1_PAD_SET_TXEN    (BIT_(7))
#define BIT_AP_APB_LVDS_LVDS_CH1_PAD_SET_TXDRV_3    (BIT_(6))
#define BIT_AP_APB_LVDS_LVDS_CH1_PAD_SET_TXDRV_2    (BIT_(5))
#define BIT_AP_APB_LVDS_LVDS_CH1_PAD_SET_TXDRV_1    (BIT_(4))
#define BIT_AP_APB_LVDS_LVDS_CH1_PAD_SET_TXDRV_0    (BIT_(3))
#define BIT_AP_APB_LVDS_LVDS_CH1_PAD_SET_TX_CM    (BIT_(2))
#define BIT_AP_APB_LVDS_LVDS_CH1_PAD_SET_RTERM_EN    (BIT_(1))
#define BIT_AP_APB_LVDS_LVDS_CH1_PAD_SET_BIAS_EN    (BIT_(0))

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_LVDS_LVDS_CH_2
// Register Offset : 0x30000
// Description     :
//--------------------------------------------------------------------------
#define REG_AP_APB_LVDS_LVDS_CH_2 (LVDS_APB_AB0_BASE_ADDR + (0x30000<<0))
#define LVDS_CH_2_ENABLE_FIELD_OFFSET 31
#define LVDS_CH_2_ENABLE_FIELD_SIZE 1
#define LVDS_CH_2_MUX_FIELD_OFFSET 23
#define LVDS_CH_2_MUX_FIELD_SIZE 2
#define LVDS_CH_2_DUALODD_FIELD_OFFSET 22
#define LVDS_CH_2_DUALODD_FIELD_SIZE 1
#define LVDS_CH_2_LANE_UPDATE_FIELD_OFFSET 7
#define LVDS_CH_2_LANE_UPDATE_FIELD_SIZE 15
#define LVDS_CH_2_FRAME_MASK_FIELD_OFFSET 5
#define LVDS_CH_2_FRAME_MASK_FIELD_SIZE 2
#define LVDS_CH_2_VSYNC_POL_FIELD_OFFSET 4
#define LVDS_CH_2_VSYNC_POL_FIELD_SIZE 1
#define LVDS_CH_2_FORMAT_FIELD_OFFSET 3
#define LVDS_CH_2_FORMAT_FIELD_SIZE 1
#define LVDS_CH_2_BPP_FIELD_OFFSET 1
#define LVDS_CH_2_BPP_FIELD_SIZE 2
#define LVDS_CH_2_DUALMODE_FIELD_OFFSET 0
#define LVDS_CH_2_DUALMODE_FIELD_SIZE 1

#define BIT_AP_APB_LVDS_LVDS_CH_2_ENABLE    (BIT_(31))
#define BIT_AP_APB_LVDS_LVDS_CH_2_MUX_1    (BIT_(24))
#define BIT_AP_APB_LVDS_LVDS_CH_2_MUX_0    (BIT_(23))
#define BIT_AP_APB_LVDS_LVDS_CH_2_DUALODD    (BIT_(22))
#define BIT_AP_APB_LVDS_LVDS_CH_2_LANE_UPDATE_14    (BIT_(21))
#define BIT_AP_APB_LVDS_LVDS_CH_2_LANE_UPDATE_13    (BIT_(20))
#define BIT_AP_APB_LVDS_LVDS_CH_2_LANE_UPDATE_12    (BIT_(19))
#define BIT_AP_APB_LVDS_LVDS_CH_2_LANE_UPDATE_11    (BIT_(18))
#define BIT_AP_APB_LVDS_LVDS_CH_2_LANE_UPDATE_10    (BIT_(17))
#define BIT_AP_APB_LVDS_LVDS_CH_2_LANE_UPDATE_9    (BIT_(16))
#define BIT_AP_APB_LVDS_LVDS_CH_2_LANE_UPDATE_8    (BIT_(15))
#define BIT_AP_APB_LVDS_LVDS_CH_2_LANE_UPDATE_7    (BIT_(14))
#define BIT_AP_APB_LVDS_LVDS_CH_2_LANE_UPDATE_6    (BIT_(13))
#define BIT_AP_APB_LVDS_LVDS_CH_2_LANE_UPDATE_5    (BIT_(12))
#define BIT_AP_APB_LVDS_LVDS_CH_2_LANE_UPDATE_4    (BIT_(11))
#define BIT_AP_APB_LVDS_LVDS_CH_2_LANE_UPDATE_3    (BIT_(10))
#define BIT_AP_APB_LVDS_LVDS_CH_2_LANE_UPDATE_2    (BIT_(9))
#define BIT_AP_APB_LVDS_LVDS_CH_2_LANE_UPDATE_1    (BIT_(8))
#define BIT_AP_APB_LVDS_LVDS_CH_2_LANE_UPDATE_0    (BIT_(7))
#define BIT_AP_APB_LVDS_LVDS_CH_2_FRAME_MASK_1    (BIT_(6))
#define BIT_AP_APB_LVDS_LVDS_CH_2_FRAME_MASK_0    (BIT_(5))
#define BIT_AP_APB_LVDS_LVDS_CH_2_VSYNC_POL    (BIT_(4))
#define BIT_AP_APB_LVDS_LVDS_CH_2_FORMAT    (BIT_(3))
#define BIT_AP_APB_LVDS_LVDS_CH_2_BPP_1    (BIT_(2))
#define BIT_AP_APB_LVDS_LVDS_CH_2_BPP_0    (BIT_(1))
#define BIT_AP_APB_LVDS_LVDS_CH_2_DUALMODE    (BIT_(0))

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_LVDS_LVDS_CLOCK_2
// Register Offset : 0x30004
// Description     :
//--------------------------------------------------------------------------
#define REG_AP_APB_LVDS_LVDS_CLOCK_2 (LVDS_APB_AB0_BASE_ADDR + (0x30004<<0))
#define LVDS_CLOCK_2_DIV_NUM_DBG_FIELD_OFFSET 11
#define LVDS_CLOCK_2_DIV_NUM_DBG_FIELD_SIZE 4
#define LVDS_CLOCK_2_DIV_NUM_LVDS_FIELD_OFFSET 7
#define LVDS_CLOCK_2_DIV_NUM_LVDS_FIELD_SIZE 4
#define LVDS_CLOCK_2_GATING_ACK_FIELD_OFFSET 6
#define LVDS_CLOCK_2_GATING_ACK_FIELD_SIZE 1
#define LVDS_CLOCK_2_GATING_EN_FIELD_OFFSET 1
#define LVDS_CLOCK_2_GATING_EN_FIELD_SIZE 5
#define LVDS_CLOCK_2_SRC_SEL_FIELD_OFFSET 0
#define LVDS_CLOCK_2_SRC_SEL_FIELD_SIZE 1

#define BIT_AP_APB_LVDS_LVDS_CLOCK_2_DIV_NUM_DBG_3    (BIT_(14))
#define BIT_AP_APB_LVDS_LVDS_CLOCK_2_DIV_NUM_DBG_2    (BIT_(13))
#define BIT_AP_APB_LVDS_LVDS_CLOCK_2_DIV_NUM_DBG_1    (BIT_(12))
#define BIT_AP_APB_LVDS_LVDS_CLOCK_2_DIV_NUM_DBG_0    (BIT_(11))
#define BIT_AP_APB_LVDS_LVDS_CLOCK_2_DIV_NUM_LVDS_3    (BIT_(10))
#define BIT_AP_APB_LVDS_LVDS_CLOCK_2_DIV_NUM_LVDS_2    (BIT_(9))
#define BIT_AP_APB_LVDS_LVDS_CLOCK_2_DIV_NUM_LVDS_1    (BIT_(8))
#define BIT_AP_APB_LVDS_LVDS_CLOCK_2_DIV_NUM_LVDS_0    (BIT_(7))
#define BIT_AP_APB_LVDS_LVDS_CLOCK_2_GATING_ACK    (BIT_(6))
#define BIT_AP_APB_LVDS_LVDS_CLOCK_2_GATING_EN_4    (BIT_(5))
#define BIT_AP_APB_LVDS_LVDS_CLOCK_2_GATING_EN_3    (BIT_(4))
#define BIT_AP_APB_LVDS_LVDS_CLOCK_2_GATING_EN_2    (BIT_(3))
#define BIT_AP_APB_LVDS_LVDS_CLOCK_2_GATING_EN_1    (BIT_(2))
#define BIT_AP_APB_LVDS_LVDS_CLOCK_2_GATING_EN_0    (BIT_(1))
#define BIT_AP_APB_LVDS_LVDS_CLOCK_2_SRC_SEL    (BIT_(0))

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_LVDS_LVDS_CH2_PAD_COM_SET
// Register Offset : 0x30008
// Description     :
//--------------------------------------------------------------------------
#define REG_AP_APB_LVDS_LVDS_CH2_PAD_COM_SET (LVDS_APB_AB0_BASE_ADDR + (0x30008<<0))
#define LVDS_CH2_PAD_COM_SET_LVDS_TRIM_FIELD_OFFSET 14
#define LVDS_CH2_PAD_COM_SET_LVDS_TRIM_FIELD_SIZE 3
#define LVDS_CH2_PAD_COM_SET_TEST_TXD_P_FIELD_OFFSET 13
#define LVDS_CH2_PAD_COM_SET_TEST_TXD_P_FIELD_SIZE 1
#define LVDS_CH2_PAD_COM_SET_TEST_TXD_N_FIELD_OFFSET 12
#define LVDS_CH2_PAD_COM_SET_TEST_TXD_N_FIELD_SIZE 1
#define LVDS_CH2_PAD_COM_SET_TEST_SCHMITT_EN_FIELD_OFFSET 11
#define LVDS_CH2_PAD_COM_SET_TEST_SCHMITT_EN_FIELD_SIZE 1
#define LVDS_CH2_PAD_COM_SET_TEST_RXEN_FIELD_OFFSET 10
#define LVDS_CH2_PAD_COM_SET_TEST_RXEN_FIELD_SIZE 1
#define LVDS_CH2_PAD_COM_SET_TEST_RXCM_EN_FIELD_OFFSET 9
#define LVDS_CH2_PAD_COM_SET_TEST_RXCM_EN_FIELD_SIZE 1
#define LVDS_CH2_PAD_COM_SET_TEST_PULLDN_FIELD_OFFSET 8
#define LVDS_CH2_PAD_COM_SET_TEST_PULLDN_FIELD_SIZE 1
#define LVDS_CH2_PAD_COM_SET_TEST_OEN_P_FIELD_OFFSET 7
#define LVDS_CH2_PAD_COM_SET_TEST_OEN_P_FIELD_SIZE 1
#define LVDS_CH2_PAD_COM_SET_TEST_OEN_N_FIELD_OFFSET 6
#define LVDS_CH2_PAD_COM_SET_TEST_OEN_N_FIELD_SIZE 1
#define LVDS_CH2_PAD_COM_SET_TEST_IEN_P_FIELD_OFFSET 5
#define LVDS_CH2_PAD_COM_SET_TEST_IEN_P_FIELD_SIZE 1
#define LVDS_CH2_PAD_COM_SET_TEST_IEN_N_FIELD_OFFSET 4
#define LVDS_CH2_PAD_COM_SET_TEST_IEN_N_FIELD_SIZE 1

#define BIT_AP_APB_LVDS_LVDS_CH2_PAD_COM_SET_LVDS_TRIM_2    (BIT_(16))
#define BIT_AP_APB_LVDS_LVDS_CH2_PAD_COM_SET_LVDS_TRIM_1    (BIT_(15))
#define BIT_AP_APB_LVDS_LVDS_CH2_PAD_COM_SET_LVDS_TRIM_0    (BIT_(14))
#define BIT_AP_APB_LVDS_LVDS_CH2_PAD_COM_SET_TEST_TXD_P    (BIT_(13))
#define BIT_AP_APB_LVDS_LVDS_CH2_PAD_COM_SET_TEST_TXD_N    (BIT_(12))
#define BIT_AP_APB_LVDS_LVDS_CH2_PAD_COM_SET_TEST_SCHMITT_EN    (BIT_(11))
#define BIT_AP_APB_LVDS_LVDS_CH2_PAD_COM_SET_TEST_RXEN    (BIT_(10))
#define BIT_AP_APB_LVDS_LVDS_CH2_PAD_COM_SET_TEST_RXCM_EN    (BIT_(9))
#define BIT_AP_APB_LVDS_LVDS_CH2_PAD_COM_SET_TEST_PULLDN    (BIT_(8))
#define BIT_AP_APB_LVDS_LVDS_CH2_PAD_COM_SET_TEST_OEN_P    (BIT_(7))
#define BIT_AP_APB_LVDS_LVDS_CH2_PAD_COM_SET_TEST_OEN_N    (BIT_(6))
#define BIT_AP_APB_LVDS_LVDS_CH2_PAD_COM_SET_TEST_IEN_P    (BIT_(5))
#define BIT_AP_APB_LVDS_LVDS_CH2_PAD_COM_SET_TEST_IEN_N    (BIT_(4))

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_LVDS_LVDS_CH2_PAD_SET
// Register Offset : 0x30010
// Description     :
//--------------------------------------------------------------------------
#define REG_AP_APB_LVDS_LVDS_CH2_PAD_SET (LVDS_APB_AB0_BASE_ADDR + (0x30010<<0))
#define LVDS_CH2_PAD_SET_RXDA_FIELD_OFFSET 11
#define LVDS_CH2_PAD_SET_RXDA_FIELD_SIZE 1
#define LVDS_CH2_PAD_SET_RXD_P_FIELD_OFFSET 10
#define LVDS_CH2_PAD_SET_RXD_P_FIELD_SIZE 1
#define LVDS_CH2_PAD_SET_RXD_N_FIELD_OFFSET 9
#define LVDS_CH2_PAD_SET_RXD_N_FIELD_SIZE 1
#define LVDS_CH2_PAD_SET_VBIAS_SEL_FIELD_OFFSET 8
#define LVDS_CH2_PAD_SET_VBIAS_SEL_FIELD_SIZE 1
#define LVDS_CH2_PAD_SET_TXEN_FIELD_OFFSET 7
#define LVDS_CH2_PAD_SET_TXEN_FIELD_SIZE 1
#define LVDS_CH2_PAD_SET_TXDRV_FIELD_OFFSET 3
#define LVDS_CH2_PAD_SET_TXDRV_FIELD_SIZE 4
#define LVDS_CH2_PAD_SET_TX_CM_FIELD_OFFSET 2
#define LVDS_CH2_PAD_SET_TX_CM_FIELD_SIZE 1
#define LVDS_CH2_PAD_SET_RTERM_EN_FIELD_OFFSET 1
#define LVDS_CH2_PAD_SET_RTERM_EN_FIELD_SIZE 1
#define LVDS_CH2_PAD_SET_BIAS_EN_FIELD_OFFSET 0
#define LVDS_CH2_PAD_SET_BIAS_EN_FIELD_SIZE 1

#define BIT_AP_APB_LVDS_LVDS_CH2_PAD_SET_RXDA    (BIT_(11))
#define BIT_AP_APB_LVDS_LVDS_CH2_PAD_SET_RXD_P    (BIT_(10))
#define BIT_AP_APB_LVDS_LVDS_CH2_PAD_SET_RXD_N    (BIT_(9))
#define BIT_AP_APB_LVDS_LVDS_CH2_PAD_SET_VBIAS_SEL    (BIT_(8))
#define BIT_AP_APB_LVDS_LVDS_CH2_PAD_SET_TXEN    (BIT_(7))
#define BIT_AP_APB_LVDS_LVDS_CH2_PAD_SET_TXDRV_3    (BIT_(6))
#define BIT_AP_APB_LVDS_LVDS_CH2_PAD_SET_TXDRV_2    (BIT_(5))
#define BIT_AP_APB_LVDS_LVDS_CH2_PAD_SET_TXDRV_1    (BIT_(4))
#define BIT_AP_APB_LVDS_LVDS_CH2_PAD_SET_TXDRV_0    (BIT_(3))
#define BIT_AP_APB_LVDS_LVDS_CH2_PAD_SET_TX_CM    (BIT_(2))
#define BIT_AP_APB_LVDS_LVDS_CH2_PAD_SET_RTERM_EN    (BIT_(1))
#define BIT_AP_APB_LVDS_LVDS_CH2_PAD_SET_BIAS_EN    (BIT_(0))

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_LVDS_LVDS_CH_3
// Register Offset : 0x40000
// Description     :
//--------------------------------------------------------------------------
#define REG_AP_APB_LVDS_LVDS_CH_3 (LVDS_APB_AB0_BASE_ADDR + (0x40000<<0))
#define LVDS_CH_3_ENABLE_FIELD_OFFSET 31
#define LVDS_CH_3_ENABLE_FIELD_SIZE 1
#define LVDS_CH_3_MUX_FIELD_OFFSET 23
#define LVDS_CH_3_MUX_FIELD_SIZE 2
#define LVDS_CH_3_DUALODD_FIELD_OFFSET 22
#define LVDS_CH_3_DUALODD_FIELD_SIZE 1
#define LVDS_CH_3_LANE_UPDATE_FIELD_OFFSET 7
#define LVDS_CH_3_LANE_UPDATE_FIELD_SIZE 15
#define LVDS_CH_3_FRAME_MASK_FIELD_OFFSET 5
#define LVDS_CH_3_FRAME_MASK_FIELD_SIZE 2
#define LVDS_CH_3_VSYNC_POL_FIELD_OFFSET 4
#define LVDS_CH_3_VSYNC_POL_FIELD_SIZE 1
#define LVDS_CH_3_FORMAT_FIELD_OFFSET 3
#define LVDS_CH_3_FORMAT_FIELD_SIZE 1
#define LVDS_CH_3_BPP_FIELD_OFFSET 1
#define LVDS_CH_3_BPP_FIELD_SIZE 2
#define LVDS_CH_3_DUALMODE_FIELD_OFFSET 0
#define LVDS_CH_3_DUALMODE_FIELD_SIZE 1

#define BIT_AP_APB_LVDS_LVDS_CH_3_ENABLE    (BIT_(31))
#define BIT_AP_APB_LVDS_LVDS_CH_3_MUX_1    (BIT_(24))
#define BIT_AP_APB_LVDS_LVDS_CH_3_MUX_0    (BIT_(23))
#define BIT_AP_APB_LVDS_LVDS_CH_3_DUALODD    (BIT_(22))
#define BIT_AP_APB_LVDS_LVDS_CH_3_LANE_UPDATE_14    (BIT_(21))
#define BIT_AP_APB_LVDS_LVDS_CH_3_LANE_UPDATE_13    (BIT_(20))
#define BIT_AP_APB_LVDS_LVDS_CH_3_LANE_UPDATE_12    (BIT_(19))
#define BIT_AP_APB_LVDS_LVDS_CH_3_LANE_UPDATE_11    (BIT_(18))
#define BIT_AP_APB_LVDS_LVDS_CH_3_LANE_UPDATE_10    (BIT_(17))
#define BIT_AP_APB_LVDS_LVDS_CH_3_LANE_UPDATE_9    (BIT_(16))
#define BIT_AP_APB_LVDS_LVDS_CH_3_LANE_UPDATE_8    (BIT_(15))
#define BIT_AP_APB_LVDS_LVDS_CH_3_LANE_UPDATE_7    (BIT_(14))
#define BIT_AP_APB_LVDS_LVDS_CH_3_LANE_UPDATE_6    (BIT_(13))
#define BIT_AP_APB_LVDS_LVDS_CH_3_LANE_UPDATE_5    (BIT_(12))
#define BIT_AP_APB_LVDS_LVDS_CH_3_LANE_UPDATE_4    (BIT_(11))
#define BIT_AP_APB_LVDS_LVDS_CH_3_LANE_UPDATE_3    (BIT_(10))
#define BIT_AP_APB_LVDS_LVDS_CH_3_LANE_UPDATE_2    (BIT_(9))
#define BIT_AP_APB_LVDS_LVDS_CH_3_LANE_UPDATE_1    (BIT_(8))
#define BIT_AP_APB_LVDS_LVDS_CH_3_LANE_UPDATE_0    (BIT_(7))
#define BIT_AP_APB_LVDS_LVDS_CH_3_FRAME_MASK_1    (BIT_(6))
#define BIT_AP_APB_LVDS_LVDS_CH_3_FRAME_MASK_0    (BIT_(5))
#define BIT_AP_APB_LVDS_LVDS_CH_3_VSYNC_POL    (BIT_(4))
#define BIT_AP_APB_LVDS_LVDS_CH_3_FORMAT    (BIT_(3))
#define BIT_AP_APB_LVDS_LVDS_CH_3_BPP_1    (BIT_(2))
#define BIT_AP_APB_LVDS_LVDS_CH_3_BPP_0    (BIT_(1))
#define BIT_AP_APB_LVDS_LVDS_CH_3_DUALMODE    (BIT_(0))

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_LVDS_LVDS_CLOCK_3
// Register Offset : 0x40004
// Description     :
//--------------------------------------------------------------------------
#define REG_AP_APB_LVDS_LVDS_CLOCK_3 (LVDS_APB_AB0_BASE_ADDR + (0x40004<<0))
#define LVDS_CLOCK_3_DIV_NUM_DBG_FIELD_OFFSET 11
#define LVDS_CLOCK_3_DIV_NUM_DBG_FIELD_SIZE 4
#define LVDS_CLOCK_3_DIV_NUM_LVDS_FIELD_OFFSET 7
#define LVDS_CLOCK_3_DIV_NUM_LVDS_FIELD_SIZE 4
#define LVDS_CLOCK_3_GATING_ACK_FIELD_OFFSET 6
#define LVDS_CLOCK_3_GATING_ACK_FIELD_SIZE 1
#define LVDS_CLOCK_3_GATING_EN_FIELD_OFFSET 1
#define LVDS_CLOCK_3_GATING_EN_FIELD_SIZE 5
#define LVDS_CLOCK_3_SRC_SEL_FIELD_OFFSET 0
#define LVDS_CLOCK_3_SRC_SEL_FIELD_SIZE 1

#define BIT_AP_APB_LVDS_LVDS_CLOCK_3_DIV_NUM_DBG_3    (BIT_(14))
#define BIT_AP_APB_LVDS_LVDS_CLOCK_3_DIV_NUM_DBG_2    (BIT_(13))
#define BIT_AP_APB_LVDS_LVDS_CLOCK_3_DIV_NUM_DBG_1    (BIT_(12))
#define BIT_AP_APB_LVDS_LVDS_CLOCK_3_DIV_NUM_DBG_0    (BIT_(11))
#define BIT_AP_APB_LVDS_LVDS_CLOCK_3_DIV_NUM_LVDS_3    (BIT_(10))
#define BIT_AP_APB_LVDS_LVDS_CLOCK_3_DIV_NUM_LVDS_2    (BIT_(9))
#define BIT_AP_APB_LVDS_LVDS_CLOCK_3_DIV_NUM_LVDS_1    (BIT_(8))
#define BIT_AP_APB_LVDS_LVDS_CLOCK_3_DIV_NUM_LVDS_0    (BIT_(7))
#define BIT_AP_APB_LVDS_LVDS_CLOCK_3_GATING_ACK    (BIT_(6))
#define BIT_AP_APB_LVDS_LVDS_CLOCK_3_GATING_EN_4    (BIT_(5))
#define BIT_AP_APB_LVDS_LVDS_CLOCK_3_GATING_EN_3    (BIT_(4))
#define BIT_AP_APB_LVDS_LVDS_CLOCK_3_GATING_EN_2    (BIT_(3))
#define BIT_AP_APB_LVDS_LVDS_CLOCK_3_GATING_EN_1    (BIT_(2))
#define BIT_AP_APB_LVDS_LVDS_CLOCK_3_GATING_EN_0    (BIT_(1))
#define BIT_AP_APB_LVDS_LVDS_CLOCK_3_SRC_SEL    (BIT_(0))

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_LVDS_LVDS_CH3_PAD_COM_SET
// Register Offset : 0x40008
// Description     :
//--------------------------------------------------------------------------
#define REG_AP_APB_LVDS_LVDS_CH3_PAD_COM_SET (LVDS_APB_AB0_BASE_ADDR + (0x40008<<0))
#define LVDS_CH3_PAD_COM_SET_LVDS_TRIM_FIELD_OFFSET 14
#define LVDS_CH3_PAD_COM_SET_LVDS_TRIM_FIELD_SIZE 3
#define LVDS_CH3_PAD_COM_SET_TEST_TXD_P_FIELD_OFFSET 13
#define LVDS_CH3_PAD_COM_SET_TEST_TXD_P_FIELD_SIZE 1
#define LVDS_CH3_PAD_COM_SET_TEST_TXD_N_FIELD_OFFSET 12
#define LVDS_CH3_PAD_COM_SET_TEST_TXD_N_FIELD_SIZE 1
#define LVDS_CH3_PAD_COM_SET_TEST_SCHMITT_EN_FIELD_OFFSET 11
#define LVDS_CH3_PAD_COM_SET_TEST_SCHMITT_EN_FIELD_SIZE 1
#define LVDS_CH3_PAD_COM_SET_TEST_RXEN_FIELD_OFFSET 10
#define LVDS_CH3_PAD_COM_SET_TEST_RXEN_FIELD_SIZE 1
#define LVDS_CH3_PAD_COM_SET_TEST_RXCM_EN_FIELD_OFFSET 9
#define LVDS_CH3_PAD_COM_SET_TEST_RXCM_EN_FIELD_SIZE 1
#define LVDS_CH3_PAD_COM_SET_TEST_PULLDN_FIELD_OFFSET 8
#define LVDS_CH3_PAD_COM_SET_TEST_PULLDN_FIELD_SIZE 1
#define LVDS_CH3_PAD_COM_SET_TEST_OEN_P_FIELD_OFFSET 7
#define LVDS_CH3_PAD_COM_SET_TEST_OEN_P_FIELD_SIZE 1
#define LVDS_CH3_PAD_COM_SET_TEST_OEN_N_FIELD_OFFSET 6
#define LVDS_CH3_PAD_COM_SET_TEST_OEN_N_FIELD_SIZE 1
#define LVDS_CH3_PAD_COM_SET_TEST_IEN_P_FIELD_OFFSET 5
#define LVDS_CH3_PAD_COM_SET_TEST_IEN_P_FIELD_SIZE 1
#define LVDS_CH3_PAD_COM_SET_TEST_IEN_N_FIELD_OFFSET 4
#define LVDS_CH3_PAD_COM_SET_TEST_IEN_N_FIELD_SIZE 1

#define BIT_AP_APB_LVDS_LVDS_CH3_PAD_COM_SET_LVDS_TRIM_2    (BIT_(16))
#define BIT_AP_APB_LVDS_LVDS_CH3_PAD_COM_SET_LVDS_TRIM_1    (BIT_(15))
#define BIT_AP_APB_LVDS_LVDS_CH3_PAD_COM_SET_LVDS_TRIM_0    (BIT_(14))
#define BIT_AP_APB_LVDS_LVDS_CH3_PAD_COM_SET_TEST_TXD_P    (BIT_(13))
#define BIT_AP_APB_LVDS_LVDS_CH3_PAD_COM_SET_TEST_TXD_N    (BIT_(12))
#define BIT_AP_APB_LVDS_LVDS_CH3_PAD_COM_SET_TEST_SCHMITT_EN    (BIT_(11))
#define BIT_AP_APB_LVDS_LVDS_CH3_PAD_COM_SET_TEST_RXEN    (BIT_(10))
#define BIT_AP_APB_LVDS_LVDS_CH3_PAD_COM_SET_TEST_RXCM_EN    (BIT_(9))
#define BIT_AP_APB_LVDS_LVDS_CH3_PAD_COM_SET_TEST_PULLDN    (BIT_(8))
#define BIT_AP_APB_LVDS_LVDS_CH3_PAD_COM_SET_TEST_OEN_P    (BIT_(7))
#define BIT_AP_APB_LVDS_LVDS_CH3_PAD_COM_SET_TEST_OEN_N    (BIT_(6))
#define BIT_AP_APB_LVDS_LVDS_CH3_PAD_COM_SET_TEST_IEN_P    (BIT_(5))
#define BIT_AP_APB_LVDS_LVDS_CH3_PAD_COM_SET_TEST_IEN_N    (BIT_(4))

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_LVDS_LVDS_CH3_PAD_SET
// Register Offset : 0x40010
// Description     :
//--------------------------------------------------------------------------
#define REG_AP_APB_LVDS_LVDS_CH3_PAD_SET (LVDS_APB_AB0_BASE_ADDR + (0x40010<<0))
#define LVDS_CH3_PAD_SET_RXDA_FIELD_OFFSET 11
#define LVDS_CH3_PAD_SET_RXDA_FIELD_SIZE 1
#define LVDS_CH3_PAD_SET_RXD_P_FIELD_OFFSET 10
#define LVDS_CH3_PAD_SET_RXD_P_FIELD_SIZE 1
#define LVDS_CH3_PAD_SET_RXD_N_FIELD_OFFSET 9
#define LVDS_CH3_PAD_SET_RXD_N_FIELD_SIZE 1
#define LVDS_CH3_PAD_SET_VBIAS_SEL_FIELD_OFFSET 8
#define LVDS_CH3_PAD_SET_VBIAS_SEL_FIELD_SIZE 1
#define LVDS_CH3_PAD_SET_TXEN_FIELD_OFFSET 7
#define LVDS_CH3_PAD_SET_TXEN_FIELD_SIZE 1
#define LVDS_CH3_PAD_SET_TXDRV_FIELD_OFFSET 3
#define LVDS_CH3_PAD_SET_TXDRV_FIELD_SIZE 4
#define LVDS_CH3_PAD_SET_TX_CM_FIELD_OFFSET 2
#define LVDS_CH3_PAD_SET_TX_CM_FIELD_SIZE 1
#define LVDS_CH3_PAD_SET_RTERM_EN_FIELD_OFFSET 1
#define LVDS_CH3_PAD_SET_RTERM_EN_FIELD_SIZE 1
#define LVDS_CH3_PAD_SET_BIAS_EN_FIELD_OFFSET 0
#define LVDS_CH3_PAD_SET_BIAS_EN_FIELD_SIZE 1

#define BIT_AP_APB_LVDS_LVDS_CH3_PAD_SET_RXDA    (BIT_(11))
#define BIT_AP_APB_LVDS_LVDS_CH3_PAD_SET_RXD_P    (BIT_(10))
#define BIT_AP_APB_LVDS_LVDS_CH3_PAD_SET_RXD_N    (BIT_(9))
#define BIT_AP_APB_LVDS_LVDS_CH3_PAD_SET_VBIAS_SEL    (BIT_(8))
#define BIT_AP_APB_LVDS_LVDS_CH3_PAD_SET_TXEN    (BIT_(7))
#define BIT_AP_APB_LVDS_LVDS_CH3_PAD_SET_TXDRV_3    (BIT_(6))
#define BIT_AP_APB_LVDS_LVDS_CH3_PAD_SET_TXDRV_2    (BIT_(5))
#define BIT_AP_APB_LVDS_LVDS_CH3_PAD_SET_TXDRV_1    (BIT_(4))
#define BIT_AP_APB_LVDS_LVDS_CH3_PAD_SET_TXDRV_0    (BIT_(3))
#define BIT_AP_APB_LVDS_LVDS_CH3_PAD_SET_TX_CM    (BIT_(2))
#define BIT_AP_APB_LVDS_LVDS_CH3_PAD_SET_RTERM_EN    (BIT_(1))
#define BIT_AP_APB_LVDS_LVDS_CH3_PAD_SET_BIAS_EN    (BIT_(0))



#endif
