/*
 * Semidrive X9 platform SID header file
 *
 * Copyright (C) 2019, Semidrive  Communications Inc.
 *
 * This file is licensed under a dual GPLv2 or X11 license.
 */

/*
 * This file is automatically generated by Semidrive.
 */

#ifndef DT_BINDINGS_MEMORY_X9_SID_H
#define DT_BINDINGS_MEMORY_X9_SID_H

/* =========================
 *        Stream IDs
 * =========================
 */
#define	X9_SID_DMA1 8
#define	X9_SID_DC1 19
#define	X9_SID_VPU1 29
#define	X9_SID_VPU2 30
#define	X9_SID_GPU1_OS1 56
#define	X9_SID_GPU2_OS1 64

#endif
