/*
 * clk-sec.c
 *
 *
 * Copyright(c); 2018 Semidrive
 *
 * Author: Alex Chen <qing.chen@semidrive.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 */

#include <linux/slab.h>
#include <linux/clk.h>
#include <linux/clk-provider.h>
#include <linux/mfd/syscon.h>
#include <linux/regmap.h>
#include <linux/reboot.h>
#include <linux/rational.h>
#include <linux/of_address.h>
#include "clk.h"
#include "ckgen.h"
#include "clk-sec.h"

/**
 * Register a clock branch.
 * Most clock branches have a form like
 *
 * src1 --|--\
 *		  |M |--[GATE]-[DIV]-
 * src2 --|--/
 *
 * sometimes without one of those components.
 */
//intern
enum SEC_CLKIN SEC_CLK_table_SEC_PLAT[] = {
	SEC_CLKIN_0, SEC_CLKIN_1, SEC_CLKIN_2, SEC_CLKIN_3, SEC_CLKIN_9,
	SEC_CLKIN_14, SEC_CLKIN_4, SEC_CLKIN_5
};
enum SEC_CLKIN SEC_CLK_table_MP_PLAT[] = {
	SEC_CLKIN_0, SEC_CLKIN_1, SEC_CLKIN_2, SEC_CLKIN_3, SEC_CLKIN_9,
	SEC_CLKIN_14, SEC_CLKIN_4, SEC_CLKIN_5
};
enum SEC_CLKIN SEC_CLK_table_SPARE0[] = {
	SEC_CLKIN_0, SEC_CLKIN_1, SEC_CLKIN_2, SEC_CLKIN_3, SEC_CLKIN_9,
	SEC_CLKIN_14, SEC_CLKIN_4, SEC_CLKIN_5
};
enum SEC_CLKIN SEC_CLK_table_SPARE1[] = {
	SEC_CLKIN_0, SEC_CLKIN_1, SEC_CLKIN_2, SEC_CLKIN_3, SEC_CLKIN_9,
	SEC_CLKIN_14, SEC_CLKIN_4, SEC_CLKIN_5
};
enum SEC_CLKIN SEC_CLK_table_CE2[] = {
	SEC_CLKIN_0, SEC_CLKIN_1, SEC_CLKIN_2, SEC_CLKIN_3, SEC_CLKIN_14,
	SEC_CLKIN_9, SEC_CLKIN_4, SEC_CLKIN_5
};
enum SEC_CLKIN SEC_CLK_table_ADC_SPARE2[] = {
	SEC_CLKIN_0, SEC_CLKIN_1, SEC_CLKIN_2, SEC_CLKIN_3, SEC_CLKIN_14,
	SEC_CLKIN_9, SEC_CLKIN_5, SEC_CLKIN_19
};
enum SEC_CLKIN SEC_CLK_table_I2C_SPI_UART_SEC[] = {
	SEC_CLKIN_0, SEC_CLKIN_1, SEC_CLKIN_2, SEC_CLKIN_3, SEC_CLKIN_7,
	SEC_CLKIN_8, SEC_CLKIN_18, SEC_CLKIN_6
};
enum SEC_CLKIN SEC_CLK_table_EMMC1234[] = {
	SEC_CLKIN_0, SEC_CLKIN_1, SEC_CLKIN_2, SEC_CLKIN_3, SEC_CLKIN_15,
	SEC_CLKIN_11, SEC_CLKIN_17, SEC_CLKIN_5
};
enum SEC_CLKIN SEC_CLK_table_ENET2_TX_RMII_PHY_REF[] = {
	SEC_CLKIN_0, SEC_CLKIN_1, SEC_CLKIN_2, SEC_CLKIN_3, SEC_CLKIN_12
};
enum SEC_CLKIN SEC_CLK_table_ENET2_TIMER_SEC[] = {
	SEC_CLKIN_0, SEC_CLKIN_1, SEC_CLKIN_2, SEC_CLKIN_3, SEC_CLKIN_10,
	SEC_CLKIN_14, SEC_CLKIN_15, SEC_CLKIN_5
};
enum SEC_CLKIN SEC_CLK_table_SPDIF1234[] = {
	SEC_CLKIN_0, SEC_CLKIN_1, SEC_CLKIN_2, SEC_CLKIN_3, SEC_CLKIN_19,
	SEC_CLKIN_24, SEC_CLKIN_16, SEC_CLKIN_8
};
enum SEC_CLKIN SEC_CLK_table_OSPI2[] = {
	SEC_CLKIN_0, SEC_CLKIN_1, SEC_CLKIN_2, SEC_CLKIN_3, SEC_CLKIN_11,
	SEC_CLKIN_16, SEC_CLKIN_17, SEC_CLKIN_15
};
enum SEC_CLKIN SEC_CLK_table_TIMER3TO8_PWM3TO8[] = {
	SEC_CLKIN_0, SEC_CLKIN_1, SEC_CLKIN_2, SEC_CLKIN_3, SEC_CLKIN_15,
	SEC_CLKIN_27, SEC_CLKIN_5, SEC_CLKIN_23
};
enum SEC_CLKIN SEC_CLK_table_I2S_MCLK2_MC1_SC3[] = {
	SEC_CLKIN_0, SEC_CLKIN_1, SEC_CLKIN_2, SEC_CLKIN_29, SEC_CLKIN_19,
	SEC_CLKIN_24, SEC_CLKIN_15, SEC_CLKIN_5
};
enum SEC_CLKIN SEC_CLK_table_I2S_MCLK3_MC2_SC5[] = {
	SEC_CLKIN_0, SEC_CLKIN_1, SEC_CLKIN_2, SEC_CLKIN_31, SEC_CLKIN_19,
	SEC_CLKIN_24, SEC_CLKIN_15, SEC_CLKIN_5
};
enum SEC_CLKIN SEC_CLK_table_I2S_SC4_SC7[] = {
	SEC_CLKIN_0, SEC_CLKIN_1, SEC_CLKIN_2, SEC_CLKIN_30, SEC_CLKIN_19,
	SEC_CLKIN_24, SEC_CLKIN_15, SEC_CLKIN_5
};
enum SEC_CLKIN SEC_CLK_table_I2S_SC6_SC8[] = {
	SEC_CLKIN_0, SEC_CLKIN_1, SEC_CLKIN_2, SEC_CLKIN_32, SEC_CLKIN_19,
	SEC_CLKIN_24, SEC_CLKIN_15, SEC_CLKIN_5
};
enum SEC_CLKIN SEC_CLK_table_CSI_MCLK12[] = {
	SEC_CLKIN_0, SEC_CLKIN_1, SEC_CLKIN_2, SEC_CLKIN_3, SEC_CLKIN_6,
	SEC_CLKIN_21, SEC_CLKIN_14, SEC_CLKIN_10
};
enum SEC_CLKIN SEC_CLK_table_GIC_4_5[] = {
	SEC_CLKIN_0, SEC_CLKIN_1, SEC_CLKIN_2, SEC_CLKIN_3, SEC_CLKIN_10,
	SEC_CLKIN_15
};
enum SEC_CLKIN SEC_CLK_table_CAN_5_TO_20[] = {
	SEC_CLKIN_0, SEC_CLKIN_1, SEC_CLKIN_2, SEC_CLKIN_3, SEC_CLKIN_7,
	SEC_CLKIN_15, SEC_CLKIN_5, SEC_CLKIN_18
};
enum SEC_CLKIN SEC_CLK_table_TRACE[] = {
	SEC_CLKIN_0, SEC_CLKIN_1, SEC_CLKIN_2, SEC_CLKIN_3, SEC_CLKIN_11,
	SEC_CLKIN_15, SEC_CLKIN_5, SEC_CLKIN_9
};
enum SEC_CLKIN SEC_CLK_table_SYS_CNT[] = {
	SEC_CLKIN_0, SEC_CLKIN_1, SEC_CLKIN_2, SEC_CLKIN_3, SEC_CLKIN_9,
	SEC_CLKIN_14, SEC_CLKIN_4, SEC_CLKIN_19
};
enum SEC_CLKIN SEC_CLK_table_MSHC_TIMER[] = {
	SEC_CLKIN_0, SEC_CLKIN_1, SEC_CLKIN_2, SEC_CLKIN_3
};
enum SEC_CLKIN SEC_CLK_table_HPI_CLK600[] = {
	SEC_CLKIN_0, SEC_CLKIN_1, SEC_CLKIN_2, SEC_CLKIN_3, SEC_CLKIN_5,
	SEC_CLKIN_4, SEC_CLKIN_9, SEC_CLKIN_14
};
enum SEC_CLKIN SEC_CLK_table_HPI_CLK800[] = {
	SEC_CLKIN_0, SEC_CLKIN_1, SEC_CLKIN_2, SEC_CLKIN_3, SEC_CLKIN_14,
	SEC_CLKIN_4, SEC_CLKIN_9, SEC_CLKIN_5
};


#define SDRV_OUT_CLK(id, _tablename, _type, _slice_id, div_shift, div_width,	\
							_busywidth, _busyshift, _expect) \
{	\
	.clk_id = SEC_CLK_ ##id,	\
	.type = _type,	\
	.slice_id = _slice_id,	\
	.gate_id = -1,	\
	.n_parents = ARRAY_SIZE(SEC_CLK_table_ ##_tablename),	\
	.div = {	\
		.shift = div_shift,	\
		.width = div_width,	\
	},	\
	.mux_table = SEC_CLK_table_ ##_tablename,	\
	.parent_id = -1,	\
	.busywidth = _busywidth,	\
	.busyshift = _busyshift,	\
	.expect = _expect,	\
}

#define SDRV_OUT_DIVIDER(id, p_id, clk_type, _slice_id, _gate_id, div_shift, div_width,	\
								_busywidth, _busyshift, _expect)	\
{	\
	.clk_id = SEC_CLK_ ##id,	\
	.type = clk_type,	\
	.slice_id = _slice_id,	\
	.gate_id = _gate_id,	\
	.parent_id = SEC_CLK_ ##p_id,	\
	.n_parents = 1,	\
	.div = {	\
		.shift = div_shift,\
		.width = div_width,\
	},	\
	.busywidth = _busywidth,	\
	.busyshift = _busyshift,	\
	.expect = _expect,	\
}


#define SDRV_OUT_GATE(id, p_id, _gate_id)	\
{	\
	.clk_id = SEC_CLK_ ##id,	\
	.type = CLK_TYPE_GATE,	\
	.gate_id = _gate_id,	\
	.parent_id = SEC_CLK_ ##p_id,	\
	.n_parents = 1,	\
	.busywidth = 0,	\
}

#define SDRV_OUT_GATE_NOPARENT(id, _gate_id)	\
{	\
	.clk_id = SEC_CLK_ ##id,	\
	.type = CLK_TYPE_GATE,	\
	.gate_id = _gate_id,	\
	.parent_id = -1,	\
	.n_parents = 0,	\
	.busywidth = 0,	\
}

#define SDRV_INTERN_CLK_IP(id, table_name, slice_id) \
		SDRV_OUT_CLK(id##_PRE, table_name, CLK_TYPE_IP, slice_id, IP_PREDIV_SHIFT, IP_PREDIV_WIDTH, IP_PREDIV_BUSYWIDTH, IP_PREDIV_BUSYSHIFT, IP_PREDIV_EXPECT),	\
		SDRV_OUT_DIVIDER(id, id##_PRE, CLK_TYPE_IP_POST, slice_id, -1, IP_POSTDIV_SHIFT, IP_POSTDIV_WIDTH, IP_POSTDIV_BUSYWIDTH, IP_POSTDIV_BUSYSHIFT, IP_POSTDIV_EXPECT)

#define SDRV_INTERN_CLK_CORE(id, slice_id) \
		SDRV_OUT_CLK(id, id, CLK_TYPE_CORE, slice_id, CORE_DIV_SHIFT, CORE_DIV_WIDTH, CORE_DIV_BUSYWIDTH, CORE_DIV_BUSYSHIFT, CORE_DIV_EXPECT)

#define SDRV_INTERN_CLK_BUS(id, slice_id) \
		SDRV_OUT_CLK(id, id, CLK_TYPE_BUS, slice_id, BUS_POSTDIV_SHIFT, BUS_POSTDIV_WIDTH, BUS_POSTDIV_BUSYWIDTH, BUS_POSTDIV_BUSYSHIFT, BUS_POSTDIV_EXPECT)

#define SDRV_OUT_CLK_GATE(id, p_id, gate_id)	\
		SDRV_OUT_GATE(id, p_id, gate_id)

/* SEC_CLK_INTERN_MAX-SEC_CLK_INTERN_FIRST+1 */
static struct sdrv_cgu_out_clk intern_clk[] = {
	//internal clk
	SDRV_INTERN_CLK_BUS(SEC_PLAT, SEC_PLAT_BUS_SLICE_TYPE_IDX),
	SDRV_INTERN_CLK_CORE(MP_PLAT, MP_PLAT_CORE_SLICE_TYPE_IDX),
	SDRV_INTERN_CLK_IP(I2C_SEC0, I2C_SPI_UART_SEC, I2C_SEC0_IP_SLICE_TYPE_IDX),
	SDRV_INTERN_CLK_IP(I2C_SEC1, I2C_SPI_UART_SEC, I2C_SEC1_IP_SLICE_TYPE_IDX),
	SDRV_INTERN_CLK_IP(SPI_SEC0, I2C_SPI_UART_SEC, SPI_SEC0_IP_SLICE_TYPE_IDX),
	SDRV_INTERN_CLK_IP(SPI_SEC1, I2C_SPI_UART_SEC, SPI_SEC1_IP_SLICE_TYPE_IDX),
	SDRV_INTERN_CLK_IP(UART_SEC0, I2C_SPI_UART_SEC, UART_SEC0_IP_SLICE_TYPE_IDX),
	SDRV_INTERN_CLK_IP(UART_SEC1, I2C_SPI_UART_SEC, UART_SEC1_IP_SLICE_TYPE_IDX),
};
/*SEC_CLK_OUT_MAX-SEC_CLK_OUT_FIRST+1*/
static struct sdrv_cgu_out_clk out_clk[] = {
	SDRV_INTERN_CLK_BUS(SPARE0, SPARE0_BUS_SLICE_TYPE_IDX),
	SDRV_INTERN_CLK_BUS(SPARE1, SPARE1_BUS_SLICE_TYPE_IDX),
	SDRV_INTERN_CLK_IP(CE2, CE2, CE2_IP_SLICE_TYPE_IDX),
	SDRV_INTERN_CLK_IP(ADC, ADC_SPARE2, ADC_IP_SLICE_TYPE_IDX),
	SDRV_INTERN_CLK_IP(SPARE2, ADC_SPARE2, SPARE2_IP_SLICE_TYPE_IDX),
	SDRV_OUT_CLK_GATE(I2C_SEC0_5, I2C_SEC0, CKGEN_SEC_CKGATE_I2C5_INDEX),
	SDRV_OUT_CLK_GATE(I2C_SEC0_7, I2C_SEC0, CKGEN_SEC_CKGATE_I2C7_INDEX),
	SDRV_OUT_CLK_GATE(I2C_SEC0_9, I2C_SEC0, CKGEN_SEC_CKGATE_I2C9_INDEX),
	SDRV_OUT_CLK_GATE(I2C_SEC0_11, I2C_SEC0, CKGEN_SEC_CKGATE_I2C11_INDEX),
	SDRV_OUT_CLK_GATE(I2C_SEC0_13, I2C_SEC0, CKGEN_SEC_CKGATE_I2C13_INDEX),
	SDRV_OUT_CLK_GATE(I2C_SEC0_15, I2C_SEC0, CKGEN_SEC_CKGATE_I2C15_INDEX),
	SDRV_OUT_CLK_GATE(I2C_SEC1_6, I2C_SEC1, CKGEN_SEC_CKGATE_I2C6_INDEX),
	SDRV_OUT_CLK_GATE(I2C_SEC1_8, I2C_SEC1, CKGEN_SEC_CKGATE_I2C8_INDEX),
	SDRV_OUT_CLK_GATE(I2C_SEC1_10, I2C_SEC1, CKGEN_SEC_CKGATE_I2C10_INDEX),
	SDRV_OUT_CLK_GATE(I2C_SEC1_12, I2C_SEC1, CKGEN_SEC_CKGATE_I2C12_INDEX),
	SDRV_OUT_CLK_GATE(I2C_SEC1_14, I2C_SEC1, CKGEN_SEC_CKGATE_I2C14_INDEX),
	SDRV_OUT_CLK_GATE(I2C_SEC1_16, I2C_SEC1, CKGEN_SEC_CKGATE_I2C16_INDEX),
	SDRV_OUT_CLK_GATE(SPI_SEC0_5, SPI_SEC0, CKGEN_SEC_CKGATE_SPI5_INDEX),
	SDRV_OUT_CLK_GATE(SPI_SEC0_7, SPI_SEC0, CKGEN_SEC_CKGATE_SPI7_INDEX),
	SDRV_OUT_CLK_GATE(SPI_SEC1_6, SPI_SEC1, CKGEN_SEC_CKGATE_SPI6_INDEX),
	SDRV_OUT_CLK_GATE(SPI_SEC1_8, SPI_SEC1, CKGEN_SEC_CKGATE_SPI8_INDEX),
	SDRV_OUT_CLK_GATE(UART_SEC0_9, UART_SEC0, CKGEN_SEC_CKGATE_UART9_INDEX),
	SDRV_OUT_CLK_GATE(UART_SEC0_11, UART_SEC0, CKGEN_SEC_CKGATE_UART11_INDEX),
	SDRV_OUT_CLK_GATE(UART_SEC0_13, UART_SEC0, CKGEN_SEC_CKGATE_UART13_INDEX),
	SDRV_OUT_CLK_GATE(UART_SEC1_10, UART_SEC1, CKGEN_SEC_CKGATE_UART10_INDEX),
	SDRV_OUT_CLK_GATE(UART_SEC1_12, UART_SEC1, CKGEN_SEC_CKGATE_UART12_INDEX),
	SDRV_OUT_CLK_GATE(UART_SEC1_14, UART_SEC1, CKGEN_SEC_CKGATE_UART14_INDEX),
	SDRV_INTERN_CLK_IP(EMMC1, EMMC1234, EMMC1_IP_SLICE_TYPE_IDX),
	SDRV_INTERN_CLK_IP(EMMC2, EMMC1234, EMMC2_IP_SLICE_TYPE_IDX),
	SDRV_INTERN_CLK_IP(EMMC3, EMMC1234, EMMC3_IP_SLICE_TYPE_IDX),
	SDRV_INTERN_CLK_IP(EMMC4, EMMC1234, EMMC4_IP_SLICE_TYPE_IDX),
	SDRV_INTERN_CLK_IP(ENET2_TX, ENET2_TX_RMII_PHY_REF, ENET2_TX_IP_SLICE_TYPE_IDX),
	SDRV_INTERN_CLK_IP(ENET2_RMII, ENET2_TX_RMII_PHY_REF, ENET2_RMII_IP_SLICE_TYPE_IDX),
	SDRV_INTERN_CLK_IP(ENET2_PHY_REF, ENET2_TX_RMII_PHY_REF, ENET2_PHY_REF_IP_SLICE_TYPE_IDX),
	SDRV_INTERN_CLK_IP(ENET2_TIMER_SEC, ENET2_TIMER_SEC, ENET2_TIMER_SEC_IP_SLICE_TYPE_IDX),
	SDRV_INTERN_CLK_IP(SPDIF1, SPDIF1234, SPDIF1_IP_SLICE_TYPE_IDX),
	SDRV_INTERN_CLK_IP(SPDIF2, SPDIF1234, SPDIF2_IP_SLICE_TYPE_IDX),
	SDRV_INTERN_CLK_IP(SPDIF3, SPDIF1234, SPDIF3_IP_SLICE_TYPE_IDX),
	SDRV_INTERN_CLK_IP(SPDIF4, SPDIF1234, SPDIF4_IP_SLICE_TYPE_IDX),
	SDRV_INTERN_CLK_IP(OSPI2, OSPI2, OSPI2_IP_SLICE_TYPE_IDX),
	SDRV_INTERN_CLK_IP(TIMER3, TIMER3TO8_PWM3TO8, TIMER3_IP_SLICE_TYPE_IDX),
	SDRV_INTERN_CLK_IP(TIMER4, TIMER3TO8_PWM3TO8, TIMER4_IP_SLICE_TYPE_IDX),
	SDRV_INTERN_CLK_IP(TIMER5, TIMER3TO8_PWM3TO8, TIMER5_IP_SLICE_TYPE_IDX),
	SDRV_INTERN_CLK_IP(TIMER6, TIMER3TO8_PWM3TO8, TIMER6_IP_SLICE_TYPE_IDX),
	SDRV_INTERN_CLK_IP(TIMER7, TIMER3TO8_PWM3TO8, TIMER7_IP_SLICE_TYPE_IDX),
	SDRV_INTERN_CLK_IP(TIMER8, TIMER3TO8_PWM3TO8, TIMER8_IP_SLICE_TYPE_IDX),
	SDRV_INTERN_CLK_IP(PWM3, TIMER3TO8_PWM3TO8, PWM3_IP_SLICE_TYPE_IDX),
	SDRV_INTERN_CLK_IP(PWM4, TIMER3TO8_PWM3TO8, PWM4_IP_SLICE_TYPE_IDX),
	SDRV_INTERN_CLK_IP(PWM5, TIMER3TO8_PWM3TO8, PWM5_IP_SLICE_TYPE_IDX),
	SDRV_INTERN_CLK_IP(PWM6, TIMER3TO8_PWM3TO8, PWM6_IP_SLICE_TYPE_IDX),
	SDRV_INTERN_CLK_IP(PWM7, TIMER3TO8_PWM3TO8, PWM7_IP_SLICE_TYPE_IDX),
	SDRV_INTERN_CLK_IP(PWM8, TIMER3TO8_PWM3TO8, PWM8_IP_SLICE_TYPE_IDX),
	SDRV_INTERN_CLK_IP(I2S_MCLK2, I2S_MCLK2_MC1_SC3, I2S_MCLK2_IP_SLICE_TYPE_IDX),
	SDRV_INTERN_CLK_IP(I2S_MCLK3, I2S_MCLK3_MC2_SC5, I2S_MCLK3_IP_SLICE_TYPE_IDX),
	SDRV_INTERN_CLK_IP(I2S_MC1, I2S_MCLK2_MC1_SC3, I2S_MC1_IP_SLICE_TYPE_IDX),
	SDRV_INTERN_CLK_IP(I2S_MC2, I2S_MCLK3_MC2_SC5, I2S_MC2_IP_SLICE_TYPE_IDX),
	SDRV_INTERN_CLK_IP(I2S_SC3, I2S_MCLK2_MC1_SC3, I2S_SC3_IP_SLICE_TYPE_IDX),
	SDRV_INTERN_CLK_IP(I2S_SC4, I2S_SC4_SC7, I2S_SC4_IP_SLICE_TYPE_IDX),
	SDRV_INTERN_CLK_IP(I2S_SC5, I2S_MCLK3_MC2_SC5, I2S_SC5_IP_SLICE_TYPE_IDX),
	SDRV_INTERN_CLK_IP(I2S_SC6, I2S_SC6_SC8, I2S_SC6_IP_SLICE_TYPE_IDX),
	SDRV_INTERN_CLK_IP(I2S_SC7, I2S_SC4_SC7, I2S_SC7_IP_SLICE_TYPE_IDX),
	SDRV_INTERN_CLK_IP(I2S_SC8, I2S_SC6_SC8, I2S_SC8_IP_SLICE_TYPE_IDX),
	SDRV_INTERN_CLK_IP(CSI_MCLK1, CSI_MCLK12, CSI_MCLK1_IP_SLICE_TYPE_IDX),
	SDRV_INTERN_CLK_IP(CSI_MCLK2, CSI_MCLK12, CSI_MCLK2_IP_SLICE_TYPE_IDX),
	SDRV_INTERN_CLK_IP(GIC_4_5, GIC_4_5, GIC_4_5_IP_SLICE_TYPE_IDX),
	SDRV_INTERN_CLK_IP(CAN_5_TO_20, CAN_5_TO_20, CAN_5_TO_20_IP_SLICE_TYPE_IDX),
	SDRV_INTERN_CLK_IP(TRACE, TRACE, TRACE_IP_SLICE_TYPE_IDX),
	SDRV_INTERN_CLK_IP(SYS_CNT, SYS_CNT, SYS_CNT_IP_SLICE_TYPE_IDX),
	SDRV_INTERN_CLK_IP(MSHC_TIMER, MSHC_TIMER, MSHC_TIMER_IP_SLICE_TYPE_IDX),
	SDRV_INTERN_CLK_IP(HPI_CLK600, HPI_CLK600, HPI_CLK600_IP_SLICE_TYPE_IDX),
	SDRV_INTERN_CLK_IP(HPI_CLK800, HPI_CLK800, HPI_CLK800_IP_SLICE_TYPE_IDX),
	SDRV_OUT_GATE_NOPARENT(GPIO2, CKGEN_SEC_CKGATE_GPIO2_INDEX),
	SDRV_OUT_GATE_NOPARENT(GPIO3, CKGEN_SEC_CKGATE_GPIO3_INDEX),
	SDRV_OUT_GATE_NOPARENT(GPIO4, CKGEN_SEC_CKGATE_GPIO4_INDEX),
	SDRV_OUT_GATE_NOPARENT(GPIO5, CKGEN_SEC_CKGATE_GPIO5_INDEX),
	SDRV_OUT_GATE_NOPARENT(WDT3, CKGEN_SEC_CKGATE_WDT3_INDEX),
	SDRV_OUT_GATE_NOPARENT(WDT4, CKGEN_SEC_CKGATE_WDT4_INDEX),
	SDRV_OUT_GATE_NOPARENT(WDT5, CKGEN_SEC_CKGATE_WDT5_INDEX),
	SDRV_OUT_GATE_NOPARENT(WDT6, CKGEN_SEC_CKGATE_WDT6_INDEX),
	SDRV_OUT_GATE_NOPARENT(WDT7, CKGEN_SEC_CKGATE_WDT7_INDEX),
	SDRV_OUT_GATE_NOPARENT(WDT8, CKGEN_SEC_CKGATE_WDT8_INDEX),
};

static struct clk *clk_base[SEC_CLK_OUT_MAX+1];
static struct clk_onecell_data clk_base_data = {
	.clks = clk_base,
	.clk_num = (SEC_CLK_OUT_MAX+1),
};

static void __init sdrv_sec_clk_init(struct device_node *np)
{
	void __iomem *sec_reg_base;
	int i;

	sec_reg_base = of_iomap(np, 0);
	if (!sec_reg_base) {
		pr_warn("%s: failed to map address range\n", __func__);
		return;
	}
	pr_debug("reg base %p\n", sec_reg_base);
	sdrv_register_sec_plls(clk_base);

	for (i = 0; i < ARRAY_SIZE(intern_clk); i++)
		clk_base[intern_clk[i].clk_id] = sdrv_register_out_composite(np,
			sec_reg_base, &intern_clk[i], sec_clk_src_names);

	for (i = 0; i < ARRAY_SIZE(out_clk); i++)
		clk_base[out_clk[i].clk_id] = sdrv_register_out_composite(np,
			sec_reg_base, &out_clk[i], sec_clk_src_names);

	of_clk_add_provider(np, of_clk_src_onecell_get, &clk_base_data);
}

CLK_OF_DECLARE(sdrv_clk, "sd,sdrv-cgu-sec", sdrv_sec_clk_init);

