/*
 * clk-sec.h
 *
 *
 * Copyright(c); 2018 Semidrive
 *
 * Author: Alex Chen <qing.chen@semidrive.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 */

#ifndef __CLK_SEC_H
#define __CLK_SEC_H

#include "clk-sec-pll.h"
//#include <dt-bindings/clk/x9-clk.h>


//core slice id
#define MP_PLAT_CORE_SLICE_TYPE_IDX 0

//bus slice id
#define SEC_PLAT_BUS_SLICE_TYPE_IDX 0
#define SPARE0_BUS_SLICE_TYPE_IDX 1
#define SPARE1_BUS_SLICE_TYPE_IDX 2

//ip slice id
#define CE2_IP_SLICE_TYPE_IDX 0
#define ADC_IP_SLICE_TYPE_IDX 1
#define SPARE2_IP_SLICE_TYPE_IDX 2
#define I2C_SEC0_IP_SLICE_TYPE_IDX 3
#define I2C_SEC1_IP_SLICE_TYPE_IDX 4
#define SPI_SEC0_IP_SLICE_TYPE_IDX 5
#define SPI_SEC1_IP_SLICE_TYPE_IDX 6
#define UART_SEC0_IP_SLICE_TYPE_IDX 7
#define UART_SEC1_IP_SLICE_TYPE_IDX 8
#define EMMC1_IP_SLICE_TYPE_IDX 9
#define EMMC2_IP_SLICE_TYPE_IDX 10
#define EMMC3_IP_SLICE_TYPE_IDX 11
#define EMMC4_IP_SLICE_TYPE_IDX 12
#define ENET2_TX_IP_SLICE_TYPE_IDX 13
#define ENET2_RMII_IP_SLICE_TYPE_IDX 14
#define ENET2_PHY_REF_IP_SLICE_TYPE_IDX 15
#define ENET2_TIMER_SEC_IP_SLICE_TYPE_IDX 16
#define SPDIF1_IP_SLICE_TYPE_IDX 17
#define SPDIF2_IP_SLICE_TYPE_IDX 18
#define SPDIF3_IP_SLICE_TYPE_IDX 19
#define SPDIF4_IP_SLICE_TYPE_IDX 20
#define OSPI2_IP_SLICE_TYPE_IDX 21
#define TIMER3_IP_SLICE_TYPE_IDX 22
#define TIMER4_IP_SLICE_TYPE_IDX 23
#define TIMER5_IP_SLICE_TYPE_IDX 24
#define TIMER6_IP_SLICE_TYPE_IDX 25
#define TIMER7_IP_SLICE_TYPE_IDX 26
#define TIMER8_IP_SLICE_TYPE_IDX 27
#define PWM3_IP_SLICE_TYPE_IDX 28
#define PWM4_IP_SLICE_TYPE_IDX 29
#define PWM5_IP_SLICE_TYPE_IDX 30
#define PWM6_IP_SLICE_TYPE_IDX 31
#define PWM7_IP_SLICE_TYPE_IDX 32
#define PWM8_IP_SLICE_TYPE_IDX 33
#define I2S_MCLK2_IP_SLICE_TYPE_IDX 34
#define I2S_MCLK3_IP_SLICE_TYPE_IDX 35
#define I2S_MC1_IP_SLICE_TYPE_IDX 36
#define I2S_MC2_IP_SLICE_TYPE_IDX 37
#define I2S_SC3_IP_SLICE_TYPE_IDX 38
#define I2S_SC4_IP_SLICE_TYPE_IDX 39
#define I2S_SC5_IP_SLICE_TYPE_IDX 40
#define I2S_SC6_IP_SLICE_TYPE_IDX 41
#define I2S_SC7_IP_SLICE_TYPE_IDX 42
#define I2S_SC8_IP_SLICE_TYPE_IDX 43
#define CSI_MCLK1_IP_SLICE_TYPE_IDX 44
#define CSI_MCLK2_IP_SLICE_TYPE_IDX 45
#define GIC_4_5_IP_SLICE_TYPE_IDX 46
#define CAN_5_TO_20_IP_SLICE_TYPE_IDX 47
#define TRACE_IP_SLICE_TYPE_IDX 48
#define SYS_CNT_IP_SLICE_TYPE_IDX 49
#define MSHC_TIMER_IP_SLICE_TYPE_IDX 50
#define HPI_CLK600_IP_SLICE_TYPE_IDX 51
#define HPI_CLK800_IP_SLICE_TYPE_IDX 52
enum SEC_CLKIN {
	SEC_CLKIN_0,
	SEC_CLKIN_1,
	SEC_CLKIN_2,
	SEC_CLKIN_3,
	SEC_CLKIN_4,
	SEC_CLKIN_5,
	SEC_CLKIN_6,
	SEC_CLKIN_7,
	SEC_CLKIN_8,
	SEC_CLKIN_9,
	SEC_CLKIN_10,
	SEC_CLKIN_11,
	SEC_CLKIN_12,
	SEC_CLKIN_13,
	SEC_CLKIN_14,
	SEC_CLKIN_15,
	SEC_CLKIN_16,
	SEC_CLKIN_17,
	SEC_CLKIN_18,
	SEC_CLKIN_19,
	SEC_CLKIN_20,
	SEC_CLKIN_21,
	SEC_CLKIN_22,
	SEC_CLKIN_23,
	SEC_CLKIN_24,
	SEC_CLKIN_25,
	SEC_CLKIN_26,
	SEC_CLKIN_27,
	SEC_CLKIN_28,
	SEC_CLKIN_29,
	SEC_CLKIN_30,
	SEC_CLKIN_31,
	SEC_CLKIN_32,
	SEC_CLKIN_MAX = SEC_CLKIN_32,
/*intern*/
	SEC_CLK_INTERN_FIRST,
	SEC_CLK_SEC_PLAT = SEC_CLK_INTERN_FIRST,
	SEC_CLK_MP_PLAT,
	SEC_CLK_INTERN_MAX = SEC_CLK_MP_PLAT,

/*out*/
	SEC_CLK_OUT_FIRST,
	SEC_CLK_SPARE0 = SEC_CLK_OUT_FIRST,
	SEC_CLK_SPARE1,
	SEC_CLK_CE2_PRE,
	SEC_CLK_CE2,
	SEC_CLK_ADC_PRE,
	SEC_CLK_ADC,
	SEC_CLK_SPARE2_PRE,
	SEC_CLK_SPARE2,
	SEC_CLK_I2C_SEC0_PRE,
	SEC_CLK_I2C_SEC0,
	SEC_CLK_I2C_SEC0_5,
	SEC_CLK_I2C_SEC0_7,
	SEC_CLK_I2C_SEC0_9,
	SEC_CLK_I2C_SEC0_11,
	SEC_CLK_I2C_SEC0_13,
	SEC_CLK_I2C_SEC0_15,
	SEC_CLK_I2C_SEC1_PRE,
	SEC_CLK_I2C_SEC1,
	SEC_CLK_I2C_SEC1_6,
	SEC_CLK_I2C_SEC1_8,
	SEC_CLK_I2C_SEC1_10,
	SEC_CLK_I2C_SEC1_12,
	SEC_CLK_I2C_SEC1_14,
	SEC_CLK_I2C_SEC1_16,
	SEC_CLK_SPI_SEC0_PRE,
	SEC_CLK_SPI_SEC0,
	SEC_CLK_SPI_SEC0_5,
	SEC_CLK_SPI_SEC0_7,
	SEC_CLK_SPI_SEC1_PRE,
	SEC_CLK_SPI_SEC1,
	SEC_CLK_SPI_SEC1_6,
	SEC_CLK_SPI_SEC1_8,
	SEC_CLK_UART_SEC0_PRE,
	SEC_CLK_UART_SEC0,
	SEC_CLK_UART_SEC0_9,
	SEC_CLK_UART_SEC0_11,
	SEC_CLK_UART_SEC0_13,
	SEC_CLK_UART_SEC0_15,
	SEC_CLK_UART_SEC1_PRE,
	SEC_CLK_UART_SEC1,
	SEC_CLK_UART_SEC1_10,
	SEC_CLK_UART_SEC1_12,
	SEC_CLK_UART_SEC1_14,
	SEC_CLK_UART_SEC1_16,
	SEC_CLK_EMMC1_PRE,
	SEC_CLK_EMMC1,
	SEC_CLK_EMMC2_PRE,
	SEC_CLK_EMMC2,
	SEC_CLK_EMMC3_PRE,
	SEC_CLK_EMMC3,
	SEC_CLK_EMMC4_PRE,
	SEC_CLK_EMMC4,
	SEC_CLK_ENET2_TX_PRE,
	SEC_CLK_ENET2_TX,
	SEC_CLK_ENET2_RMII_PRE,
	SEC_CLK_ENET2_RMII,
	SEC_CLK_ENET2_PHY_REF_PRE,
	SEC_CLK_ENET2_PHY_REF,
	SEC_CLK_ENET2_TIMER_SEC_PRE,
	SEC_CLK_ENET2_TIMER_SEC,
	SEC_CLK_SPDIF1_PRE,
	SEC_CLK_SPDIF1,
	SEC_CLK_SPDIF2_PRE,
	SEC_CLK_SPDIF2,
	SEC_CLK_SPDIF3_PRE,
	SEC_CLK_SPDIF3,
	SEC_CLK_SPDIF4_PRE,
	SEC_CLK_SPDIF4,
	SEC_CLK_OSPI2_PRE,
	SEC_CLK_OSPI2,
	SEC_CLK_TIMER3_PRE,
	SEC_CLK_TIMER3,
	SEC_CLK_TIMER4_PRE,
	SEC_CLK_TIMER4,
	SEC_CLK_TIMER5_PRE,
	SEC_CLK_TIMER5,
	SEC_CLK_TIMER6_PRE,
	SEC_CLK_TIMER6,
	SEC_CLK_TIMER7_PRE,
	SEC_CLK_TIMER7,
	SEC_CLK_TIMER8_PRE,
	SEC_CLK_TIMER8,
	SEC_CLK_PWM3,
	SEC_CLK_PWM4,
	SEC_CLK_PWM5,
	SEC_CLK_PWM6,
	SEC_CLK_PWM7,
	SEC_CLK_PWM8,
	SEC_CLK_I2S_MCLK2,
	SEC_CLK_I2S_MCLK3,
	SEC_CLK_I2S_MC1,
	SEC_CLK_I2S_MC2,
	SEC_CLK_I2S_SC3,
	SEC_CLK_I2S_SC4,
	SEC_CLK_I2S_SC5,
	SEC_CLK_I2S_SC6,
	SEC_CLK_I2S_SC7,
	SEC_CLK_I2S_SC8,
	SEC_CLK_CSI_MCLK1,
	SEC_CLK_CSI_MCLK2,
	SEC_CLK_GIC_4_5,
	SEC_CLK_CAN_5_TO_20,
	SEC_CLK_TRACE,
	SEC_CLK_SYS_CNT,
	SEC_CLK_MSHC_TIMER,
	SEC_CLK_HPI_CLK600,
	SEC_CLK_HPI_CLK800,
	SEC_CLK_PWM3_PRE,
	SEC_CLK_PWM4_PRE,
	SEC_CLK_PWM5_PRE,
	SEC_CLK_PWM6_PRE,
	SEC_CLK_PWM7_PRE,
	SEC_CLK_PWM8_PRE,
	SEC_CLK_I2S_MCLK2_PRE,
	SEC_CLK_I2S_MCLK3_PRE,
	SEC_CLK_I2S_MC1_PRE,
	SEC_CLK_I2S_MC2_PRE,
	SEC_CLK_I2S_SC3_PRE,
	SEC_CLK_I2S_SC4_PRE,
	SEC_CLK_I2S_SC5_PRE,
	SEC_CLK_I2S_SC6_PRE,
	SEC_CLK_I2S_SC7_PRE,
	SEC_CLK_I2S_SC8_PRE,
	SEC_CLK_CSI_MCLK1_PRE,
	SEC_CLK_CSI_MCLK2_PRE,
	SEC_CLK_GIC_4_5_PRE,
	SEC_CLK_CAN_5_TO_20_PRE,
	SEC_CLK_TRACE_PRE,
	SEC_CLK_SYS_CNT_PRE,
	SEC_CLK_MSHC_TIMER_PRE,
	SEC_CLK_HPI_CLK600_PRE,
	SEC_CLK_HPI_CLK800_PRE,
	SEC_CLK_GPIO2,
	SEC_CLK_GPIO3,
	SEC_CLK_GPIO4,
	SEC_CLK_GPIO5,
	SEC_CLK_WDT3,
	SEC_CLK_WDT4,
	SEC_CLK_WDT5,
	SEC_CLK_WDT6,
	SEC_CLK_WDT7,
	SEC_CLK_WDT8,
	SEC_CLK_OUT_MAX = SEC_CLK_WDT8,
};

static const char *sec_clk_src_names[] = {
	[SEC_CLKIN_0]	= "SEC_RC_24M",
	[SEC_CLKIN_1]	= "SEC_RC_RTC",
	[SEC_CLKIN_2]	= "SEC_XTAL_24M",
	[SEC_CLKIN_3]	= "SEC_XTAL_RTC",
	[SEC_CLKIN_4]	= "SEC_PLL3",
	[SEC_CLKIN_5]	= "SEC_PLL3_DIVA",
	[SEC_CLKIN_6]	= "SEC_PLL3_DIVB",
	[SEC_CLKIN_7]	= "SEC_PLL3_DIVC",
	[SEC_CLKIN_8]	= "SEC_PLL3_DIVD",
	[SEC_CLKIN_9]	= "SEC_PLL4",
	[SEC_CLKIN_10]	= "SEC_PLL4_DIVA",
	[SEC_CLKIN_11]	= "SEC_PLL4_DIVB",
	[SEC_CLKIN_12]	= "SEC_PLL4_DIVC",
	[SEC_CLKIN_13]	= "SEC_PLL4_DIVD",
	[SEC_CLKIN_14]	= "SEC_PLL5",
	[SEC_CLKIN_15]	= "SEC_PLL5_DIVA",
	[SEC_CLKIN_16]	= "SEC_PLL5_DIVB",
	[SEC_CLKIN_17]	= "SEC_PLL5_DIVC",
	[SEC_CLKIN_18]	= "SEC_PLL5_DIVD",
	[SEC_CLKIN_19]	= "SEC_PLL6",
	[SEC_CLKIN_20]	= "SEC_PLL6_DIVA",
	[SEC_CLKIN_21]	= "SEC_PLL6_DIVB",
	[SEC_CLKIN_22]	= "SEC_PLL6_DIVC",
	[SEC_CLKIN_23]	= "SEC_PLL6_DIVD",
	[SEC_CLKIN_24]	= "SEC_PLL7",
	[SEC_CLKIN_25]	= "SEC_PLL7_DIVA",
	[SEC_CLKIN_26]	= "SEC_PLL7_DIVB",
	[SEC_CLKIN_27]	= "SEC_PLL7_DIVC",
	[SEC_CLKIN_28]	= "SEC_PLL7_DIVD",
	[SEC_CLKIN_29]	= "SEC_EXT_AUD1",
	[SEC_CLKIN_30]	= "SEC_EXT_AUD2",
	[SEC_CLKIN_31]	= "SEC_EXT_AUD3",
	[SEC_CLKIN_32]	= "SEC_EXT_AUD4",
/*intern*/
	[SEC_CLK_SEC_PLAT] = "SEC_PLAT",
	[SEC_CLK_MP_PLAT] = "MP_PLAT",
/*out*/
	[SEC_CLK_SPARE0] = "SEC_SPARE0",
	[SEC_CLK_SPARE1] = "SEC_SPARE1",
	[SEC_CLK_CE2_PRE] = "SEC_CE2_PRE",
	[SEC_CLK_CE2] = "SEC_CE2",
	[SEC_CLK_ADC_PRE] = "SEC_ADC_PRE",
	[SEC_CLK_ADC] = "SEC_ADC",
	[SEC_CLK_SPARE2_PRE] = "SEC_SPARE2_PRE",
	[SEC_CLK_SPARE2] = "SEC_SPARE2",
	[SEC_CLK_I2C_SEC0_PRE] = "SEC_I2C_SEC0_PRE",
	[SEC_CLK_I2C_SEC0] = "SEC_I2C_SEC0",
	[SEC_CLK_I2C_SEC0_5] = "SEC_I2C_SEC0_5",
	[SEC_CLK_I2C_SEC0_7] = "SEC_I2C_SEC0_7",
	[SEC_CLK_I2C_SEC0_9] = "SEC_I2C_SEC0_9",
	[SEC_CLK_I2C_SEC0_11] = "SEC_I2C_SEC0_11",
	[SEC_CLK_I2C_SEC0_13] = "SEC_I2C_SEC0_13",
	[SEC_CLK_I2C_SEC0_15] = "SEC_I2C_SEC0_15",
	[SEC_CLK_I2C_SEC1_PRE] = "SEC_I2C_SEC1_PRE",
	[SEC_CLK_I2C_SEC1] = "SEC_I2C_SEC1",
	[SEC_CLK_I2C_SEC1_6] = "SEC_I2C_SEC1_6",
	[SEC_CLK_I2C_SEC1_8] = "SEC_I2C_SEC1_8",
	[SEC_CLK_I2C_SEC1_10] = "SEC_I2C_SEC1_10",
	[SEC_CLK_I2C_SEC1_12] = "SEC_I2C_SEC1_12",
	[SEC_CLK_I2C_SEC1_14] = "SEC_I2C_SEC1_14",
	[SEC_CLK_I2C_SEC1_16] = "SEC_I2C_SEC1_16",
	[SEC_CLK_SPI_SEC0_PRE] = "SEC_SPI_SEC0_PRE",
	[SEC_CLK_SPI_SEC0] = "SEC_SPI_SEC0",
	[SEC_CLK_SPI_SEC0_5] = "SEC_SPI_SEC0_5",
	[SEC_CLK_SPI_SEC0_7] = "SEC_SPI_SEC0_7",
	[SEC_CLK_SPI_SEC1_PRE] = "SEC_SPI_SEC1_PRE",
	[SEC_CLK_SPI_SEC1] = "SEC_SPI_SEC1",
	[SEC_CLK_SPI_SEC1_6] = "SEC_SPI_SEC1_6",
	[SEC_CLK_SPI_SEC1_8] = "SEC_SPI_SEC1_8",
	[SEC_CLK_UART_SEC0_PRE] = "SEC_UART_SEC0_PRE",
	[SEC_CLK_UART_SEC0] = "SEC_UART_SEC0",
	[SEC_CLK_UART_SEC0_9] = "SEC_UART_SEC0_9",
	[SEC_CLK_UART_SEC0_11] = "SEC_UART_SEC0_11",
	[SEC_CLK_UART_SEC0_13] = "SEC_UART_SEC0_13",
	[SEC_CLK_UART_SEC0_15] = "SEC_UART_SEC0_15",
	[SEC_CLK_UART_SEC1_PRE] = "SEC_UART_SEC1_PRE",
	[SEC_CLK_UART_SEC1] = "SEC_UART_SEC1",
	[SEC_CLK_UART_SEC1_10] = "SEC_UART_SEC1_10",
	[SEC_CLK_UART_SEC1_12] = "SEC_UART_SEC1_12",
	[SEC_CLK_UART_SEC1_14] = "SEC_UART_SEC1_14",
	[SEC_CLK_UART_SEC1_16] = "SEC_UART_SEC1_16",
	[SEC_CLK_EMMC1_PRE] = "SEC_EMMC1_PRE",
	[SEC_CLK_EMMC2_PRE] = "SEC_EMMC2_PRE",
	[SEC_CLK_EMMC3_PRE] = "SEC_EMMC3_PRE",
	[SEC_CLK_EMMC4_PRE] = "SEC_EMMC4_PRE",
	[SEC_CLK_EMMC1] = "SEC_EMMC1",
	[SEC_CLK_EMMC2] = "SEC_EMMC2",
	[SEC_CLK_EMMC3] = "SEC_EMMC3",
	[SEC_CLK_EMMC4] = "SEC_EMMC4",
	[SEC_CLK_ENET2_TX_PRE] = "SEC_ENET2_TX_PRE",
	[SEC_CLK_ENET2_RMII_PRE] = "SEC_ENET2_RMII_PRE",
	[SEC_CLK_ENET2_PHY_REF_PRE] = "SEC_ENET2_PHY_REF_PRE",
	[SEC_CLK_ENET2_TIMER_SEC_PRE] = "SEC_ENET2_TIMER_SEC_PRE",
	[SEC_CLK_ENET2_TX] = "SEC_ENET2_TX",
	[SEC_CLK_ENET2_RMII] = "SEC_ENET2_RMII",
	[SEC_CLK_ENET2_PHY_REF] = "SEC_ENET2_PHY_REF",
	[SEC_CLK_ENET2_TIMER_SEC] = "SEC_ENET2_TIMER_SEC",
	[SEC_CLK_SPDIF1] = "SEC_SPDIF1",
	[SEC_CLK_SPDIF2] = "SEC_SPDIF2",
	[SEC_CLK_SPDIF3] = "SEC_SPDIF3",
	[SEC_CLK_SPDIF4] = "SEC_SPDIF4",
	[SEC_CLK_OSPI2] = "SEC_OSPI2",
	[SEC_CLK_TIMER3] = "SEC_TIMER3",
	[SEC_CLK_TIMER4] = "SEC_TIMER4",
	[SEC_CLK_TIMER5] = "SEC_TIMER5",
	[SEC_CLK_TIMER6] = "SEC_TIMER6",
	[SEC_CLK_TIMER7] = "SEC_TIMER7",
	[SEC_CLK_TIMER8] = "SEC_TIMER8",
	[SEC_CLK_SPDIF1_PRE] = "SEC_SPDIF1_PRE",
	[SEC_CLK_SPDIF2_PRE] = "SEC_SPDIF2_PRE",
	[SEC_CLK_SPDIF3_PRE] = "SEC_SPDIF3_PRE",
	[SEC_CLK_SPDIF4_PRE] = "SEC_SPDIF4_PRE",
	[SEC_CLK_OSPI2_PRE] = "SEC_OSPI2_PRE",
	[SEC_CLK_TIMER3_PRE] = "SEC_TIMER3_PRE",
	[SEC_CLK_TIMER4_PRE] = "SEC_TIMER4_PRE",
	[SEC_CLK_TIMER5_PRE] = "SEC_TIMER5_PRE",
	[SEC_CLK_TIMER6_PRE] = "SEC_TIMER6_PRE",
	[SEC_CLK_TIMER7_PRE] = "SEC_TIMER7_PRE",
	[SEC_CLK_TIMER8_PRE] = "SEC_TIMER8_PRE",
	[SEC_CLK_PWM3] = "SEC_PWM3",
	[SEC_CLK_PWM4] = "SEC_PWM4",
	[SEC_CLK_PWM5] = "SEC_PWM5",
	[SEC_CLK_PWM6] = "SEC_PWM6",
	[SEC_CLK_PWM7] = "SEC_PWM7",
	[SEC_CLK_PWM8] = "SEC_PWM8",
	[SEC_CLK_I2S_MCLK2] = "SEC_I2S_MCLK2",
	[SEC_CLK_I2S_MCLK3] = "SEC_I2S_MCLK3",
	[SEC_CLK_I2S_MC1] = "SEC_I2S_MC1",
	[SEC_CLK_I2S_MC2] = "SEC_I2S_MC2",
	[SEC_CLK_I2S_SC3] = "SEC_I2S_SC3",
	[SEC_CLK_I2S_SC4] = "SEC_I2S_SC4",
	[SEC_CLK_I2S_SC5] = "SEC_I2S_SC5",
	[SEC_CLK_I2S_SC6] = "SEC_I2S_SC6",
	[SEC_CLK_I2S_SC7] = "SEC_I2S_SC7",
	[SEC_CLK_I2S_SC8] = "SEC_I2S_SC8",
	[SEC_CLK_CSI_MCLK1] = "SEC_CSI_MCLK1",
	[SEC_CLK_CSI_MCLK2] = "SEC_CSI_MCLK2",
	[SEC_CLK_GIC_4_5] = "SEC_GIC_4_5",
	[SEC_CLK_CAN_5_TO_20] = "SEC_CAN_5_TO_20",
	[SEC_CLK_TRACE] = "SEC_TRACE",
	[SEC_CLK_SYS_CNT] = "SEC_SYS_CNT",
	[SEC_CLK_MSHC_TIMER] = "SEC_MSHC_TIMER",
	[SEC_CLK_HPI_CLK600] = "SEC_HPI_CLK600",
	[SEC_CLK_HPI_CLK800] = "SEC_HPI_CLK800",
	[SEC_CLK_PWM3_PRE] = "SEC_PWM3_PRE",
	[SEC_CLK_PWM4_PRE] = "SEC_PWM4_PRE",
	[SEC_CLK_PWM5_PRE] = "SEC_PWM5_PRE",
	[SEC_CLK_PWM6_PRE] = "SEC_PWM6_PRE",
	[SEC_CLK_PWM7_PRE] = "SEC_PWM7_PRE",
	[SEC_CLK_PWM8_PRE] = "SEC_PWM8_PRE",
	[SEC_CLK_I2S_MCLK2_PRE] = "SEC_I2S_MCLK2_PRE",
	[SEC_CLK_I2S_MCLK3_PRE] = "SEC_I2S_MCLK3_PRE",
	[SEC_CLK_I2S_MC1_PRE] = "SEC_I2S_MC1_PRE",
	[SEC_CLK_I2S_MC2_PRE] = "SEC_I2S_MC2_PRE",
	[SEC_CLK_I2S_SC3_PRE] = "SEC_I2S_SC3_PRE",
	[SEC_CLK_I2S_SC4_PRE] = "SEC_I2S_SC4_PRE",
	[SEC_CLK_I2S_SC5_PRE] = "SEC_I2S_SC5_PRE",
	[SEC_CLK_I2S_SC6_PRE] = "SEC_I2S_SC6_PRE",
	[SEC_CLK_I2S_SC7_PRE] = "SEC_I2S_SC7_PRE",
	[SEC_CLK_I2S_SC8_PRE] = "SEC_I2S_SC8_PRE",
	[SEC_CLK_CSI_MCLK1_PRE] = "SEC_CSI_MCLK1_PRE",
	[SEC_CLK_CSI_MCLK2_PRE] = "SEC_CSI_MCLK2_PRE",
	[SEC_CLK_GIC_4_5_PRE] = "SEC_GIC_4_5_PRE",
	[SEC_CLK_CAN_5_TO_20_PRE] = "SEC_CAN_5_TO_20_PRE",
	[SEC_CLK_TRACE_PRE] = "SEC_TRACE_PRE",
	[SEC_CLK_SYS_CNT_PRE] = "SEC_SYS_CNT_PRE",
	[SEC_CLK_MSHC_TIMER_PRE] = "SEC_MSHC_TIMER_PRE",
	[SEC_CLK_HPI_CLK600_PRE] = "SEC_HPI_CLK600_PRE",
	[SEC_CLK_HPI_CLK800_PRE] = "SEC_HPI_CLK800_PRE",
	[SEC_CLK_GPIO2] = "SEC_GPIO2",
	[SEC_CLK_GPIO3] = "SEC_GPIO3",
	[SEC_CLK_GPIO4] = "SEC_GPIO4",
	[SEC_CLK_GPIO5] = "SEC_GPIO5",
	[SEC_CLK_WDT3] = "SEC_WDT3",
	[SEC_CLK_WDT4] = "SEC_WDT4",
	[SEC_CLK_WDT5] = "SEC_WDT5",
	[SEC_CLK_WDT6] = "SEC_WDT6",
	[SEC_CLK_WDT7] = "SEC_WDT7",
	[SEC_CLK_WDT8] = "SEC_WDT8",

};
#endif

