/*
 * clk-disp.h
 *
 *
 * Copyright(c); 2018 Semidrive
 *
 * Author: Alex Chen <qing.chen@semidrive.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 */
#ifndef __CLK_DISP_H
#define __CLK_DISP_H

#include "clk-disp-pll.h"
//core slice id
//bus slice id
#define DISP_BUS_SLICE_TYPE_IDX 0


//ip slice id
#define MIPI_CSI1_PIX_IP_SLICE_TYPE_IDX 0
#define MIPI_CSI2_PIX_IP_SLICE_TYPE_IDX 1
#define MIPI_CSI3_PIX_IP_SLICE_TYPE_IDX 2
#define DP1_IP_SLICE_TYPE_IDX 3
#define DP2_IP_SLICE_TYPE_IDX 4
#define DP3_IP_SLICE_TYPE_IDX 5
#define DC5_IP_SLICE_TYPE_IDX 6
#define DC1_IP_SLICE_TYPE_IDX 7
#define DC2_IP_SLICE_TYPE_IDX 8
#define DC3_IP_SLICE_TYPE_IDX 9
#define DC4_IP_SLICE_TYPE_IDX 10
#define SPARE1_IP_SLICE_TYPE_IDX 11
#define DC5_ALT_DSP_IP_SLICE_TYPE_IDX 12
#define EXT_AUD1_IP_SLICE_TYPE_IDX 13
#define EXT_AUD2_IP_SLICE_TYPE_IDX 14
#define EXT_AUD3_IP_SLICE_TYPE_IDX 15
#define EXT_AUD4_IP_SLICE_TYPE_IDX 16

enum DISP_CLKIN {
	DISP_CLKIN_0,
	DISP_CLKIN_1,
	DISP_CLKIN_2,
	DISP_CLKIN_3,
	DISP_CLKIN_4,
	DISP_CLKIN_5,
	DISP_CLKIN_6,
	DISP_CLKIN_7,
	DISP_CLKIN_8,
	DISP_CLKIN_9,
	DISP_CLKIN_10,
	DISP_CLKIN_11,
	DISP_CLKIN_12,
	DISP_CLKIN_13,
	DISP_CLKIN_14,
	DISP_CLKIN_15,
	DISP_CLKIN_16,
	DISP_CLKIN_17,
	DISP_CLKIN_18,
	DISP_CLKIN_MAX = DISP_CLKIN_18,

	/*out*/
	DISP_CLK_OUT_FIRST,
	DISP_CLK_MIPI_CSI1_PIX = DISP_CLK_OUT_FIRST,
	DISP_CLK_MIPI_CSI2_PIX,
	DISP_CLK_MIPI_CSI3_PIX,
	DISP_CLK_DP1,
	DISP_CLK_DP2,
	DISP_CLK_DP3,
	DISP_CLK_DC5,
	DISP_CLK_DC1,
	DISP_CLK_DC2,
	DISP_CLK_DC3,
	DISP_CLK_DC4,
	DISP_CLK_SPARE1,
	DISP_CLK_DC5_ALT_DSP,
	DISP_CLK_DISP_BUS,
	DISP_CLK_EXT_AUD1,
	DISP_CLK_EXT_AUD2,
	DISP_CLK_EXT_AUD3,
	DISP_CLK_EXT_AUD4,
	DISP_CLK_MIPI_CSI1,
	DISP_CLK_MIPI_CSI2,
	DISP_CLK_MIPI_CSI3,
	DISP_CLK_CSI1,
	DISP_CLK_CSI2,
	DISP_CLK_CSI3,
	DISP_CLK_MIPI_CSI1_PIX_PRE,
	DISP_CLK_MIPI_CSI2_PIX_PRE,
	DISP_CLK_MIPI_CSI3_PIX_PRE,
	DISP_CLK_DP1_PRE,
	DISP_CLK_DP2_PRE,
	DISP_CLK_DP3_PRE,
	DISP_CLK_DC5_PRE,
	DISP_CLK_DC1_PRE,
	DISP_CLK_DC2_PRE,
	DISP_CLK_DC3_PRE,
	DISP_CLK_DC4_PRE,
	DISP_CLK_SPARE1_PRE,
	DISP_CLK_DC5_ALT_DSP_PRE,
	DISP_CLK_EXT_AUD1_PRE,
	DISP_CLK_EXT_AUD2_PRE,
	DISP_CLK_EXT_AUD3_PRE,
	DISP_CLK_EXT_AUD4_PRE,
	DISP_CLK_OUT_MAX = DISP_CLK_EXT_AUD4_PRE,
};

static const char *disp_clk_src_names[] = {
	[DISP_CLKIN_0] = "DISP_RC_24M",
	[DISP_CLKIN_1] = "DISP_RC_RTC",
	[DISP_CLKIN_2] = "DISP_XTAL_24M",
	[DISP_CLKIN_3] = "DISP_XTAL_RTC",
	[DISP_CLKIN_4] = "PLL_DISP",
	[DISP_CLKIN_5] = "PLL_DISP_DIVA",
	[DISP_CLKIN_6] = "PLL_DISP_DIVB",
	[DISP_CLKIN_7] = "PLL_LVDS1",
	[DISP_CLKIN_8] = "PLL_LVDS1_DIVA",
	[DISP_CLKIN_9] = "PLL_LVDS1_DIVB",
	[DISP_CLKIN_10] = "PLL_LVDS2",
	[DISP_CLKIN_11] = "PLL_LVDS2_DIVA",
	[DISP_CLKIN_12] = "PLL_LVDS2_DIVB",
	[DISP_CLKIN_13] = "PLL_LVDS3",
	[DISP_CLKIN_14] = "PLL_LVDS3_DIVA",
	[DISP_CLKIN_15] = "PLL_LVDS3_DIVB",
	[DISP_CLKIN_16] = "PLL_LVDS4",
	[DISP_CLKIN_17] = "PLL_LVDS4_DIVA",
	[DISP_CLKIN_18] = "PLL_LVDS4_DIVB",

	/*out*/
	[DISP_CLK_MIPI_CSI1_PIX] = "MIPI_CSI1_PIX",
	[DISP_CLK_MIPI_CSI2_PIX] = "MIPI_CSI2_PIX",
	[DISP_CLK_MIPI_CSI3_PIX] = "MIPI_CSI3_PIX",
	[DISP_CLK_DP1] = "DP1",
	[DISP_CLK_DP2] = "DP2",
	[DISP_CLK_DP3] = "DP3",
	[DISP_CLK_DC5] = "DC5",
	[DISP_CLK_DC1] = "DC1",
	[DISP_CLK_DC2] = "DC2",
	[DISP_CLK_DC3] = "DC3",
	[DISP_CLK_DC4] = "DC4",
	[DISP_CLK_SPARE1] = "DISP_SPARE1",
	[DISP_CLK_DC5_ALT_DSP] = "DC5_ALT_DSP",
	[DISP_CLK_DISP_BUS] = "DISP_BUS",
	[DISP_CLK_EXT_AUD1] = "EXT_AUD1",
	[DISP_CLK_EXT_AUD2] = "EXT_AUD2",
	[DISP_CLK_EXT_AUD3] = "EXT_AUD3",
	[DISP_CLK_EXT_AUD4] = "EXT_AUD4",
	[DISP_CLK_MIPI_CSI1] = "MIPI_CSI1",
	[DISP_CLK_MIPI_CSI2] = "MIPI_CSI2",
	[DISP_CLK_MIPI_CSI3] = "MIPI_CSI3",
	[DISP_CLK_CSI1] = "CSI1",
	[DISP_CLK_CSI2] = "CSI2",
	[DISP_CLK_CSI3] = "CSI3",
	[DISP_CLK_MIPI_CSI1_PIX_PRE] = "MIPI_CSI1_PIX_PRE",
	[DISP_CLK_MIPI_CSI2_PIX_PRE] = "MIPI_CSI2_PIX_PRE",
	[DISP_CLK_MIPI_CSI3_PIX_PRE] = "MIPI_CSI3_PIX_PRE",
	[DISP_CLK_DP1_PRE] = "DP1_PRE",
	[DISP_CLK_DP2_PRE] = "DP2_PRE",
	[DISP_CLK_DP3_PRE] = "DP3_PRE",
	[DISP_CLK_DC5_PRE] = "DC5_PRE",
	[DISP_CLK_DC1_PRE] = "DC1_PRE",
	[DISP_CLK_DC2_PRE] = "DC2_PRE",
	[DISP_CLK_DC3_PRE] = "DC3_PRE",
	[DISP_CLK_DC4_PRE] = "DC4_PRE",
	[DISP_CLK_SPARE1_PRE] = "DISP_SPARE1_PRE",
	[DISP_CLK_DC5_ALT_DSP_PRE] = "DC5_ALT_DSP_PRE",
	[DISP_CLK_EXT_AUD1_PRE] = "EXT_AUD1_PRE",
	[DISP_CLK_EXT_AUD2_PRE] = "EXT_AUD2_PRE",
	[DISP_CLK_EXT_AUD3_PRE] = "EXT_AUD3_PRE",
	[DISP_CLK_EXT_AUD4_PRE] = "EXT_AUD4_PRE",
};
#endif

