# SPDX-License-Identifier: GPL-2.0
#
# Semidrive Clock specific Makefile
#

#KBUILD_CFLAGS   += -Werror
obj-y	+= ckgen.o sc_pfpll.o
obj-y	+= clk.o clk-composite-sd.o clk-pll.o
obj-y	+= clk-soc.o clk-soc-pll.o
obj-y	+= clk-sec.o clk-sec-pll.o
obj-y	+= clk-disp.o clk-disp-pll.o
