# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the drm device driver.  This driver provides support for the
# Direct Rendering Infrastructure (DRI) in XFree86 4.1.0 and higher.

sdrvdrm-y := \
	dsi/dwc_mipi_dsi_host.o \
	dsi/sdrv-mipi-dsi.o

obj-$(CONFIG_DRM_SEMIDRIVE) += sdrvdrm.o
