dtb-$(CONFIG_ARCH_SEMIDRIVE_X9) += x9-high-evb-vm-cluster.dtb
dtb-$(CONFIG_ARCH_SEMIDRIVE_X9) += x9-high-evb-vm-ivi.dtb
dtb-$(CONFIG_ARCH_SEMIDRIVE_X9) += x9-high-evb-xen.dtb
dtb-$(CONFIG_ARCH_SEMIDRIVE_X9) += x9-high-ref-vm-cluster.dtb
dtb-$(CONFIG_ARCH_SEMIDRIVE_X9) += x9-high-ref-vm-ivi.dtb
dtb-$(CONFIG_ARCH_SEMIDRIVE_X9) += x9-high-ref-xen.dtb
dtb-$(CONFIG_ARCH_SEMIDRIVE_X9) += x9-high-evb-vm-cluster.dtb
dtb-$(CONFIG_ARCH_SEMIDRIVE_X9) += x9-high-ref-serdes-vm-cluster.dtb
dtb-$(CONFIG_ARCH_SEMIDRIVE_X9) += x9-high-ref-serdes-vm-ivi-vgpu.dtb
dtb-$(CONFIG_ARCH_SEMIDRIVE_X9) += x9-high-ref-serdes-vm-ivi.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
