#
# Makefile for the semidrive cpu budget cooling drivers.
#
obj-$(CONFIG_SEMIDRIVE_BUDGET_COOLING) += semidrive-budget-cooling.o

obj-$(CONFIG_SEMIDRIVE_COOLING_DEVICES) += semidrive-cooling-devices.o
