obj-$(CONFIG_SEMIDRIVE_IPCC)	+= ipcc_rpc.o ipcc_rpmsg_sample.o dc_negotiate.o xenipc-front.o xenipc-back.o vdsp.o i2c_negotiate.o chrdev.o
obj-$(CONFIG_SEMIDRIVE_SCR)	+= sdrv_scr.o
obj-$(CONFIG_ARCH_SEMIDRIVE)	+= sdrv_boardinfo_hwid.o

