obj-$(CONFIG_SEMIDRIVE_IPCC)	+= ipcc_rpc.o \
								ipcc_rpmsg_sample.o \
								rpcall.o \
								dc_negotiate.o \
								i2c_negotiate.o \
								xenipc-front.o \
								xenipc-back.o \
								vdsp.o \
								chrdev.o

obj-$(CONFIG_SEMIDRIVE_SCR)	+= sdrv_scr.o

