obj-$(CONFIG_SEMIDRIVE_IPCC)	+= ipcc_rpc.o \
								ipcc_rpmsg_sample.o \
								rpcall.o \
								rpcall-front.o \
								rpcall-back.o \
								dc_negotiate.o \
								i2c_negotiate.o \
								xenipc-front.o \
								xenipc-back.o \
								vdsp.o \
								chrdev.o \
								chrdev-front.o

obj-$(CONFIG_SEMIDRIVE_SCR)	+= sdrv_scr.o
obj-$(CONFIG_SEMIDRIVE_VCE)	+= sdrv_vce.o
obj-$(CONFIG_ARCH_SEMIDRIVE)	+= sdrv_boardinfo_hwid.o sys_counter.o
obj-$(CONFIG_SEMIDRIVE_SDPE_RPC) += sdpe_rpc.o
