# Semidrive ALSA SoC driver

snd-x9-i2s-sc-objs := x9-i2s-sc.o
obj-$(CONFIG_SND_X9_AFE_I2S_SC) += snd-x9-i2s-sc.o

snd-x9-i2s-mc-objs := x9-i2s-mc.o
obj-$(CONFIG_SND_X9_AFE_I2S_MC) += snd-x9-i2s-mc.o

snd-x9-fpga-mach-objs := x9-fpga-mach.o
obj-$(CONFIG_SND_X9_FPGA_MACH) += snd-x9-fpga-mach.o

snd-x9-evb-mach-objs := x9-evb-mach.o
obj-$(CONFIG_SND_X9_EVB_MACH) += snd-x9-evb-mach.o

