# Semidrive ALSA SoC driver

snd-sdrv-i2s-sc-objs := sdrv-i2s-sc.o
obj-$(CONFIG_SND_SDRV_AFE_I2S_SC) += snd-sdrv-i2s-sc.o

snd-sdrv-i2s-mc-objs := sdrv-i2s-mc.o
obj-$(CONFIG_SND_SDRV_AFE_I2S_MC) += snd-sdrv-i2s-mc.o

snd-x9-fpga-mach-objs := x9-fpga-mach.o
obj-$(CONFIG_SND_X9_FPGA_MACH) += snd-x9-fpga-mach.o

snd-x9-evb-mach-objs := x9-evb-mach.o
obj-$(CONFIG_SND_X9_EVB_MACH) += snd-x9-evb-mach.o

snd-g9-ref-mach-objs := g9-ref-mach.o
obj-$(CONFIG_SND_G9_REF_MACH) += snd-g9-ref-mach.o
