# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_SEMIDRIVE_X9) += x9_z1.dtb
dtb-$(CONFIG_ARCH_SEMIDRIVE_X9) += x9_z1-cpu1.dtb
dtb-$(CONFIG_ARCH_SEMIDRIVE_X9) += x9_fpga.dtb
dtb-$(CONFIG_ARCH_SEMIDRIVE_X9) += g9_ref.dtb
dtb-$(CONFIG_ARCH_SEMIDRIVE_X9) += x9_evb_1920x720.dtb
dtb-$(CONFIG_ARCH_SEMIDRIVE_X9) += x9_ref_1920x720.dtb
dtb-$(CONFIG_ARCH_SEMIDRIVE_X9) += x9_evb_memdisk.dtb
dtb-$(CONFIG_ARCH_SEMIDRIVE_X9) += x9_high_ref_ivi_dual-disp-1280x800.dtb
dtb-$(CONFIG_ARCH_SEMIDRIVE_X9) += x9_high_ref_cluster_single-disp-1920x720.dtb
dtb-$(CONFIG_ARCH_SEMIDRIVE_X9) += x9_high_ref_controlpanel.dtb
dtb-$(CONFIG_ARCH_SEMIDRIVE_X9) += x9_high_evb_ivi_dual-disp-1280x800.dtb
dtb-$(CONFIG_ARCH_SEMIDRIVE_X9) += x9_high_evb_cluster_single-disp-1920x720.dtb
dtb-$(CONFIG_ARCH_SEMIDRIVE_X9) += x9_high_evb_controlpanel.dtb

dtb-$(CONFIG_ARCH_SEMIDRIVE_X9) += x9_high_evb_native_ivi.dtb
dtb-$(CONFIG_ARCH_SEMIDRIVE_X9) += x9_high_evb_native_cluster.dtb
dtb-$(CONFIG_ARCH_SEMIDRIVE_X9) += x9_high_evb_native_controlpanel.dtb
dtb-$(CONFIG_ARCH_SEMIDRIVE_X9) += x9_high_ref_native_ivi.dtb
dtb-$(CONFIG_ARCH_SEMIDRIVE_X9) += x9_high_ref_native_cluster.dtb
dtb-$(CONFIG_ARCH_SEMIDRIVE_X9) += x9_high_ref_native_controlpanel.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
