# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_SEMIDRIVE_X9) += x9_z1.dtb
dtb-$(CONFIG_ARCH_SEMIDRIVE_X9) += x9_z1-cpu1.dtb
dtb-$(CONFIG_ARCH_SEMIDRIVE_X9) += x9_fpga.dtb
dtb-$(CONFIG_ARCH_SEMIDRIVE_X9) += x9_evb.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
